### ISSUE TITLE
recaptcha issues in beta

### ISSUE THREAD

**Issue by rainbowdashie1** [Floens/Clover#106]
after getting the message "An error occured while contacting the recaptcha service" recaptcha won't work until the app is restarted
also if the box is ticked while there's no network it will get stuck and again, the app has to be restarted

**Comment by Floens** [comment]
I added a button to hard reset the captcha, for both the legacy and normal one.
https://github.com/Floens/Clover/commit/8c0d512d528ac32d7c125485bd6f61281d098e8e
