### ISSUE TITLE
search box isn't focussed after selecting search in beta

### ISSUE THREAD

**Issue by rainbowdashie1** [Floens/Clover#107]

**Comment by pinkiewhy** [comment]
This is very annoying and I hope it gets addressed

**Comment by plumbe0** [comment]
I second that, it's very annoying. Also, if you set the light theme with Teal as the main color you can't see the caret because it overlaps with the searchbox.

**Comment by Floens** [comment]
I fixed this in https://github.com/Floens/Clover/commit/67f725f140ea3b6ccca381bdb1958255617772a5
To yet be released.
