### ISSUE TITLE
Error sending reply

### ISSUE THREAD

**Issue by Chrometrain** [Floens/Clover#108]
Error sending reply! Error appears after doing the captcha
Note: 4chan is blocked in my country

**Comment by Chrometrain** [comment]
Downloaded proxy manager original error is fixed now it just says your country is blocked due abuse

**Comment by Floens** [comment]
How can Clover fix this if it's banned in your country?

**Comment by Chrometrain** [comment]
I was hoping someone with the same problem could offer ne a program or something but you are right I should close the problem
