### ISSUE TITLE
Preload captcha on reply 

### ISSUE THREAD

**Issue by StevenGates** [Floens/Clover#111]
Is it possible to preload the captcha when we click the reply button? AFAIK, the captcha is aware of how long it's been loaded to determine if a user-test is necessary. 

Since the current setup loads the captcha only the instant before we tap it, it always questions our legitimacy and makes us pass a test. 

I'm guessing pre-loading it would allow us to sometimes bypass the test and just click the check box.

**Comment by Floens** [comment]
No I'm pretty sure this won't work, because the only considers people who are logged into their Google account for no user-test.
Reopen the issue if I'm wrong. The legacy captcha is used by default now, so it shouldn't be so much of a deal.
