### ISSUE TITLE
Error sending reply when image attached

### ISSUE THREAD

**Issue by aruv42** [Floens/Clover#112]
Sometime had this problem when posting reply with image. Error sending reply toast appeared after captcha.
That image is fine if posted using PC.

**Comment by btleffler** [comment]
It doesn't seem to be related to attaching images for me. It happens regardless recently.

**Comment by Floens** [comment]
Does the toast appear after fixed amount of time or immediately after posting?

Also please note your Android version and Clover version.

**Comment by btleffler** [comment]
Clover v1.2.11
Android Version 5.1 on DROID TURBO

It seems to happen after a long delay, my first thought was a timeout or something. I'm not sure how to go about getting better debugging info.

**Comment by Floens** [comment]
Allright, I'll do some testing.

**Comment by Floens** [comment]
This probably is a problem with the timeout being quite low on v1. Please reopen this issue if it persist on v2.
