### ISSUE TITLE
Feature Request: Large image viewing modes

### ISSUE THREAD

**Issue by Dapizzaman** [Floens/Clover#113]
I would love the options to: 

1) View expanded, auto-loaded images in the thread so you don't have to tap on the thumbnails to view them and
2) View a thread's images in a grid style. I know Beta has the grid implemented by selecting "download album," but tapping on the images only selects / deselects them for download. I'm hoping for a gallery-style image viewer.

Thanks!

**Comment by Floens** [comment]
> View expanded, auto-loaded images in the thread so you don't have to tap on the thumbnails to view them and
Like inline image viewing, causing the image to be bigger without opening the viewer? This is actually really hard to get right, and I would rather not do it.

I'm creating a separate issue for the album feature.

Please reopen if you mean something else.
