### ISSUE TITLE
Two-pane navigation in portrait

### ISSUE THREAD

**Issue by TyroneSama** [Floens/Clover#119]
My tablet is kinda small, so the two-pane navigation mode is kind of a nuisance for portrait mode. Everything gets crammed into roughly an inch of space and it's kinda distracting: in portrait, I'd much rather navigate like I do on my phone. Any chance we could get a toggle?
![screenshot_2015-10-24-14-12-06](https://cloud.githubusercontent.com/assets/8174023/10712857/02ec16de-7a5b-11e5-93c8-b3fa277aaac1.jpg)

**Comment by Floens** [comment]
I did change the left pane size to something smaller already.
There is a toggle in the advanced settings to force the mobile layout.

**Comment by TyroneSama** [comment]
Ah, thanks. I completely missed the Advanced Settings button, it's kinda tucked away up there.

**Comment by Floens** [comment]
There was a bug so this issue was still apparent in v2.1.0, but finally fixed in my dev build.
