### ISSUE TITLE
Crash when selecting board

### ISSUE THREAD

**Issue by kirby193** [Floens/Clover#120]
Whenever I open the drop down menu, the app crashes. No report, only ok.

What I've done;
Re-install
Clear cache
Clear data

This will happen off of a fresh install

Lg motion 4g
Just downloaded the newest apk (1211) as of 5 mins ago to be sure.

If you need anything else just ask.

**Comment by kirby193** [comment]
I thought I should also note that it had worked for months up until I removed a default board from the board listing. That's when it started the crashing thing.
Everything else works (pinning threads, opening and replying to them) and if i set another board as default and restart the app, it'll open that board.

**Comment by Floens** [comment]
Do you have a modified rom or do you run xposed?

**Comment by kirby193** [comment]
Xposed.

**Comment by Floens** [comment]
Like I thought, the force fast scroller module makes spinners crash.
No it's a problem the module maker has to solve, because Clover doesn't do anything special with the spinner.
