### ISSUE TITLE
Frequent freezes after the last beta update

### ISSUE THREAD

**Issue by bakugo** [Floens/Clover#126]
Using v2.1.0 on Android 5.0, the app keeps completely freezing every few minutes and needs to be restarted. Doesn't seem like it's caused by any specific action.

**Comment by ElegantMonkey** [comment]
It froze when I tried to interact with some "links", like listing the replies of a post, or going to a post.

**Comment by Lunanite** [comment]
Same here, on Android 4.4.2 on a LG Tribute. It's not tied to an action I can identify, except that it Galen's more when solving a captcha. But it will happen when I'm just reading a thread, too.

**Comment by msdsk** [comment]
Same, hangs at completely random moments; changed to the new captcha, didn't help

**Comment by jeffenns** [comment]
I get the same thing frequently on 5.1.1 / Xperia Z5. Happens most often when I click a post's image from catalog view.

**Comment by Lunanite** [comment]
I should add, it's not a 'full' freeze. If it happens whine I'm hitting the Verify button and posting, it'll post it, despite the screen being frozen.

**Comment by tumblingdown** [comment]
Seconding this. Galaxy s5 freezes when either posting or interacting with links.

**Comment by lc-guy** [comment]
I think I know where the issue comes from. 

It's from the new swipe to close thread function :accidentally swiping to the right, even just a little bit, triggers it. I guess that function is quite buggy for the time being.

**Comment by Floens** [comment]
Sorry for the late response, busy times.
As what @lc-guy has said, that might be the case because there is a function that intercepts all touches, and that might be buggy. I'm still working on it.

**Comment by Floens** [comment]
Finally fixed in https://github.com/Floens/Clover/commit/262f34dfc11287819daed5bb3edb5ed72c0a1b73
