### ISSUE TITLE
App crashes when swiping partially loaded images

### ISSUE THREAD

**Issue by Kozzaki** [Floens/Clover#127]
I've noticed that if I swipe while an image is loading, then swipe back to that image, itll fully load then the app will crash.

**Comment by Kozzaki** [comment]
Oh, Android 5.1.1 and newest release on Google play, 2.1 I think

**Comment by Kozzaki** [comment]
Lmao no response for almost a month

**Comment by Floens** [comment]
Happy?

**Comment by Kozzaki** [comment]
A little bit. Time to shitpost on /g/

**Comment by Floens** [comment]
Fix in https://github.com/Floens/Clover/commit/17cd26b6afb2f2b8919a21d6138a643774324e87
