### ISSUE TITLE
Searching board also searches thread

### ISSUE THREAD

**Issue by Yazawaniko** [Floens/Clover#131]
While browsing a thread, it will suddenly refresh and the only replies that will be shown are the first 20 or so. Very strange.

**Comment by Floens** [comment]
Dude that's like the eight report today.
It's friday night, I'll look at it tomorrow or sunday.

**Comment by riesza** [comment]
To elaborate on this: it has to do with the search box as it seems to carry over the thread search results into the actual thread.

**Comment by nv-vn** [comment]
Same here, happens when I move my finger to the left a bit (but only in certain threads). The replies aren't the first few, it just shows random ones from throughout the thread.

**Comment by Floens** [comment]
There is an issue with searching. When searching from the board screen and going to a thread, when swiping back it starts searching in the thread screen also. Will be fixed.
