### ISSUE TITLE
Enable transparent status bar for Android KitKat

### ISSUE THREAD

**Issue by SuppliedRelic** [Floens/Clover#132]
The look and feel of the application is really coming together with the Material Design makeover. It would be great if you enabled status bar transparency for 4.4.x KitKat. This would make for a more modern and immersive experience for users on older devices.

**Comment by Floens** [comment]
Kitkat doesn't have transparent status bar like in lollipop. It has a strong shade and doesn't look good imo.

**Comment by SuppliedRelic** [comment]
KitKat may not have a completely transparent status bar like Lollipop+ does but it can still be made translucent to allow the Navigation Drawer to be visible sliding beneath in a similar fashion to Lollipop. I've seen this implementation in several other applications.
