### ISSUE TITLE
Gifs not loading

### ISSUE THREAD

**Issue by Djolanderr** [Floens/Clover#133]
When I click on a gif image, it stays black or shows only the first frame of the image. The issue is there both on non-material and material wip version (2.1.0).
Thie issue started when I updated my phone firmware update on KitKat 4.4.2 mediatek device. Tried to factory reset the phone but still same :/

**Comment by Floens** [comment]
Is this on a custom rom? Might be an issue like #2 with bad graphics drivers.

**Comment by Djolanderr** [comment]
Stock rom

**Comment by Djolanderr** [comment]
But gifs load fine on other apps

**Comment by Undyinggod** [comment]
No gifs,  webms,  or images loading on htc m5 either with all current updates.  And gifs load fine elsewhere. The error message "failed to show image"  appears instead on the bottom of a grainy image.

**Comment by Djolanderr** [comment]
Update: it's no more a problem in non-material version. Somehow it magically fixed by itself.
