### ISSUE TITLE
App Randomly Hanging/Loading Slow

### ISSUE THREAD

**Issue by Veerdale** [Floens/Clover#139]
I've been using Clover for a while now, on both my old LG G1 and G3, and haven't run into any problems until recently. I just upgraded to a Samsung Galaxy S6 Edge+ a few days ago and have been encountering some unusually long load times on Clover. The G3 I just upgraded from was also running Android 5.1.1, but did not experience this problem.

The issue seems to be unusually long load times in the app, where text/threads take 5-10 seconds to  appear, and images take even longer/fail to load completely. Restarting the app does not seem to have any effect, nor does reinstalling/clearing data. Tinkering with the Clover settings also did not appear to have any effect. I have tested this on both the mobile data network and Wi-Fi, and neither seem to have much of a difference in the load times.  Surfing the 4chan website through any normal mobile browser loads the pages and images instantly and without problem.

Strangely enough, there are times where the app works normally, and it will load things quickly as it should. However, this behavior appears to be intermittent and only lasts temporarily (from 30 seconds to 2 minutes). I have tried to isolate if any sort of background service or app could be causing this, but to no avail. Seeing as Clover has usually worked for me, I would normally chalk it up to a device/OS problem, but no other apps seem to be behaving strangely like this.

**Comment by skewerr** [comment]
While I haven't noticed any slowdowns not due to a poor connection on my end, the app has hanged several times recently.

I'm browsing fine, but sometimes when I tap a thumbnail to view an image or video, the application stops in the same screen and won't react to anything. Only a restart of the app has managed to break it out of this state.

**Comment by Veerdale** [comment]
Situation has resolved itself recently. Still not sure if it was just connections issues or something else, but either way, it is no longer a problem.
