### ISSUE TITLE
cant make reverse image search

### ISSUE THREAD

**Issue by EfronC** [Floens/Clover#142]
For some reason the app doesn't let me make reverse image search with Google on Galaxy SIII, it gives the next message on Google

"The URL doesn't refer to an image, or the image is not publicly accessible."

I make the search using the option of Clover "Search image" and this started without me doing anything, one day it worked, the next don't.

**Comment by EfronC** [comment]
Sorry, a little error, this happen on Android, not only on my galaxy S3, can't make reverse search on my tablet.

**Comment by Floens** [comment]
Google fixed this some days ago.
