### ISSUE TITLE
Allow old behaviour when swiping away threads

### ISSUE THREAD

**Issue by NotAFile** [Floens/Clover#147]
Since the Material Design update, swiping away a thread will remove it from the interface entirely. I much prefer the old behaviour of simply tucking it away to the side because it allowed me to continue browsing boards while having a thread open.

I may be alone with this, but I thought I'd mention it and see if anybody else misses this feature.

**Comment by pinkiewhy** [comment]
Seconded

**Comment by Floens** [comment]
The two pane layout as Clover v1 used was deprecated a long long time ago, and it did not fit in at all with the material design guidelines.

I rewrote all the UI code in v2 and I did not want to put in a deprecated layout.

I do know that it was pretty handy from time to time. That's why I'm still planning to add a tabs based interface option.

Making all the screens swipeable was already something I added in later to keep some of the Clover v1  behavior.

**Comment by Decme** [comment]
And you wonder why people won't update from v1? Who says the code or design is deprecated? If you choose to use the code, then it remains active code.

**Comment by d9h02f** [comment]
I didn't use that feature, but Material Design is absolutely retarded so I don't really see that as a good reason to not implement the feature again.

**Comment by NotAFile** [comment]
how hard would it be to port the old code?

**Comment by Floens** [comment]
You guys would rather have tabs than a two pane layout right? Tabs can do what the two pane layout did and more.

**Comment by NotAFile** [comment]
sure, tabs would also be nice. The question I have is:

 - At which layer do we have the tabs? (Thread layer, board layer, whatever)

 - Who's Tab layout style do we steal? A tab bar takes up so much space, chrome's tab thing is clumsy.

 - How will tabs be integrated with the pinning system? With tabs, we would have two ways of keeping track of threads, which is kind of redundant, and will probably be anoying in the long run. A good integration of tabs with pinning should be a goal of the new solution.

In a way, the current pinning system is a tabs system already, just a bit clumsier.

**Comment by Floens** [comment]
>At which layer do we have the tabs? (Thread layer, board layer, whatever)
All thread like views, so the board and thread controller.

>Who's Tab layout style do we steal? A tab bar takes up so much space, chrome's tab thing is clumsy.
Tabs at the top with a short title, scrolling horizontally between them was my idea.

>How will tabs be integrated with the pinning system? With tabs, we would have two ways of keeping track of threads, which is kind of redundant, and will probably be anoying in the long run. A good integration of tabs with pinning should be a goal of the new solution.
I think replacing the whole pinning pane with what tabs are open is the way to go. Opening a thread will automatically pin (and thus save across restarts) the thread, and pressing the back button will remove it again.

**Comment by NotAFile** [comment]
> I think replacing the whole pinning pane with what tabs are open is the way to go. Opening a thread will automatically pin (and thus save across restarts) the thread, and pressing the back button will remove it again.

That was my first thought too, but I was reluctant to post it because the solution would not be very good for the way I browse.

Usually threads are one of the following:

 - crap
 - crap, but I still open them just in case
 - good
 - promising, not enough replies

In that order.

Threads I actually want to keep are rare enough that I think it should be easier to discard them than keep them.

Here's a quick idea I had for a merger of pinning and tabs, along with a masterful painting: http://imgur.com/YbitArE

It's a bit of a Tinder system: dragging right destroys the thread view as it does now, and dragging left (first drawing) opens the tabs/pins panel, dragging the thread onto that places the current thread into it (second drawing).

Edit: Upon reviewing this Idea, it seems stupid. It's just a weird way to pin threads. All we really need is to keep pinned threads loaded, or at least keep their state
