### ISSUE TITLE
Crashes When Image Album Downloads

### ISSUE THREAD

**Issue by TheDarkMysteryMan** [Floens/Clover#15]
The issues isn't within the default save directory. 

I can save normally by clicking it and it would save all the images. However, I wanted to change the storage to my external storage. So I made a new file for it (/storage/external_SD/Clover.)

And while it worked for default, changing it to an external storage dosent work. Infact, I can't save albums anywhere I put the save directory to an external. It only works for internal. When I try to save the album, the app would crash every time. It would also leave the folders behind, but no pictures.

**Comment by Floens** [comment]
This is fixed by not using the DownloadedManager for album downloads in v2.x
