### ISSUE TITLE
Downloads blank images when downloading an album

### ISSUE THREAD

**Issue by Haunter** [Floens/Clover#151]
When downloading an album full of images almost every time it will end up downloading purely black images, or images that don't exist and show up as black boxes in the gallery application

**Comment by Floens** [comment]
What android version?

**Comment by Haunter** [comment]
Note 5 on 5.1.1

**Comment by Floens** [comment]
I can't reproduce this (anymore?). Please re-open if it still fails (on the new version when it's out).
