### ISSUE TITLE
Api parse error

### ISSUE THREAD

**Issue by Haunter** [Floens/Clover#152]
When opening the program and attempting to load any boards I am receiving "api parse error"  tap to retry.

**Comment by Floens** [comment]
4chan is down atm, give it a few hours. https://github.com/Floens/ChanTracking/commit/a92e1e0f21118a97d52fdb082365f1cacd15459c

**Comment by Floens** [comment]
Please re-open this issue if it still occurs.

**Comment by ouza52** [comment]
I'm currently having the same issue but I checked and 4chan is up :/

**Comment by Floens** [comment]
What board/thread is giving you trouble?
I'm noticing 4chan is a bit slow.

**Comment by ouza52** [comment]
All of them

**Comment by Floens** [comment]
Could you create a new issue with the template filled in?
