### ISSUE TITLE
Multiple FilterTypes per filter

### ISSUE THREAD

**Issue by Efruit** [Floens/Clover#154]
Sometimes it is impossible to fully block generals without a filter that matches subject, name, and comment text. Would it be possible to change the FilterType system to match a set of fields, rather than just one?

Alternatively, an All Fields input type would probably solve the problem just as well.

**Comment by Floens** [comment]
Yeah this is planned, the current system doesn't work that great.

**Comment by Efruit** [comment]
Since we're on the topic, is an option to only match threads on the roadmap?

**Comment by Floens** [comment]
Yes that too.
