### ISSUE TITLE
Unknown Board Code

### ISSUE THREAD

**Issue by murinon** [Floens/Clover#156]
Whenever I try to add a board it says this error, the only boards I can add are the original 4. This has happened on both of my phones.

**Comment by Floens** [comment]
It should work fine if you just type in the board code. You're probably confused because the old version removed quotes and this version does not.

**Comment by murinon** [comment]
I've tried just typing k, fit, /k/, /fit/, the full urls and everything inbetween

**Comment by Floens** [comment]
Hmm works fine on my machine, try reinstalling. Might be a bug with loading the boards on startup in BoardManager.

**Comment by murinon** [comment]
It randomly started working without reinstalling. k
