### ISSUE TITLE
Playing music with webms 

### ISSUE THREAD

**Issue by NickWinston123** [Floens/Clover#158]
Hey, really liking this 4chan browser,  is there anyway to make it so when  I'm using clovers inside video player, it won't pause my music? Maybe like a mute button somewhere that mutes all sounds coming from 4chan? I browse boards like /b/ that have no sound so it's kind of pointless for it to pause my music.  Using a LGv10 if that's important,  thanks

**Comment by Floens** [comment]
Not possible afaik. It already has a workaround on android < 5.0 to stop pausing any music, but they changed some things in VideoView that make it impossible (or at least very hard because I haven't figured out a way yet.)
