### ISSUE TITLE
Request: ability to remove highlighting and replies for privacy reasons

### ISSUE THREAD

**Issue by 1excellent** [Floens/Clover#160]
I really like clover, it's honestly my favorite app out of all the chan apps available. My only concern is that clover highlights your post and there is no way to clear it and any (you)s will stay until either the thread is deleted or you have to uninstall/reinstall the app. There should be an option to clear out cache/posting history or something like that for privacy reasons because your entire posting history will be visible for as long as the thread exists. I'm aware that clover v2 has history, but it only shows what threads you visited and disabling still keeps the post highlighting.

**Comment by jocfla** [comment]
That's a great idea :D

**Comment by Floens** [comment]
I could make an option to clear the saved reply table. It's a minor feature.

**Comment by 1excellent** [comment]
Thank you Floens, it would be wonderful if you could do that.
