### ISSUE TITLE
support for HTTP proxy auth

### ISSUE THREAD

**Issue by rainbowdashie1** [Floens/Clover#163]

**Comment by Floens** [comment]
Proxy auth? Like what?

**Comment by rainbowdashie1** [comment]
username and password...

**Comment by Floens** [comment]
For what exactly? You have to tell me the protocol and service you want to use.

**Comment by rainbowdashie1** [comment]
not sure what else to tell you...
proxies support authentication to prevent unauthorised access.

**Comment by Floens** [comment]
Well I couldn't expect more from a guy called "rainbowdashie1"

**Comment by jocfla** [comment]
Maybe there's such a thing as a private proxy, I'm not sure.
**_also lol_**

**Comment by rainbowdashie1** [comment]
tbh most people are capable of understanding what authentication is
![2016-02-22_19-55-05](https://cloud.githubusercontent.com/assets/13788103/13230682/3e7a9a48-d99e-11e5-9ccd-b6922cc50e04.png)

**Comment by NHellFire** [comment]
Really? What's so difficult to understand?
Both HTTP and SOCKS proxies can support auth. Such as paid proxy services, personally hosted ones or work/school networks.

One explanation: http://science.opposingviews.com/proxy-authentication-types-3269.html

**Comment by Floens** [comment]
The [Proxy](http://developer.android.com/reference/android/net/Proxy.html) implementation of Android doesn't support authentication, and neither does the proxy option interface for the WiFI. It's out of the scope of this project to find a way around this. Try a vpn, or an app that emulates an authenticated socks proxy as a vpn.

**Comment by NHellFire** [comment]
Incorrect. You linked to **android**.net.Proxy, the app is using **java**.net.Proxy, so auth is done with java.net.Authenticator, which is available in Android.
http://developer.android.com/reference/java/net/Authenticator.html

```
$ git grep android.net.Proxy
<no results>
$ git grep java.net.Proxy
Clover/app/src/main/java/org/floens/chan/core/net/ProxiedHurlStack.java:import java.net.Proxy;
Clover/app/src/main/java/org/floens/chan/core/settings/ChanSettings.java:import java.net.Proxy;
```

**Comment by Floens** [comment]
Whoops my bad.
How would I implement authentication for the FileCache (uses okhttp) and the volley queues? 
The app supports HTTP proxies only right now ([correct me if I'm wrong](https://github.com/Floens/Clover/blob/dev/Clover/app/src/main/java/org/floens/chan/core/settings/ChanSettings.java#L271)), how is this going to work with socks proxies?
I stil think it's a feature creep.

**Comment by NHellFire** [comment]
I'm not a Java or Android dev, so I'm not sure. I'd have to look through
the code, but from other examples auth seems as simple as setting it as the
default. If SOCKS proxies are supported, java.net.Authenticator should
understand it. I could have a look it another day when I've got some free
time.

**Comment by Phoenix09** [comment]
I have this working and I have almost no Java experience

**Comment by KebabLord** [comment]
bump. implement authentication already
