### ISSUE TITLE
Can not post "You are ."

### ISSUE THREAD

**Issue by Darkflame116** [Floens/Clover#165]
I tried making a thread, and after correctly doing to capcha it denied it and said "Error: You are .". What does that even mean? I posted not two days ago without issue.

**Comment by Floens** [comment]
It means you are banned, but the "banned" part is left out because of a bug.

**Comment by Darkflame116** [comment]
Thanks for the reply, i was able to post like an hour after so i closed it, but good to know why it happened. No clue why i had a temp ban tho. Thanks again
