### ISSUE TITLE
Request: Mark posts as posted by you

### ISSUE THREAD

**Issue by Lunanite** [Floens/Clover#168]
Posts you make are automatically set to highlight and inform on comment (the illusive (You)), but sometimes that's lost when reloading Clover after its closed, or on phone restart. If we could have an option to choose a post to mark like a post by the user, that'd be great. Also would be nice for those who post from mobile and PC, as we could still be notified on reply across devices.

**Comment by Floens** [comment]
It should never get lost.
Related to #160

**Comment by Lunanite** [comment]
I've had it happen, when it does, it occurs after a complete restart of Clover (for example, when downloading thread albums, if my connection is lost/switched to wi-fi during the download, Clover will stop downloading, and hitting the notification will not stop it, so I have to Force Stop it in Settings), and upon returning to Clover and a thread, my comments will no longer be marked as mine. I should probably open a ticket for the album download issue as well.
