### ISSUE TITLE
4chan Passes don't apply in reports

### ISSUE THREAD

**Issue by Lunanite** [Floens/Clover#169]
Though it even mentions in the report form that 4chan pass users can bypass it, you still have to solve the captcha when reporting, despite the pass working when posting.

**Comment by Floens** [comment]
It's a very niche feature, that's why I didn't implement it. The report form changes from time to time unlike the post form so it's not something maintainable.

**Comment by Lunanite** [comment]
That was fast, thanks Floens.

I didn't notice it but now that I think about it, it does change often. I'll just try to stop going to threads where I need to report every other post.
