### ISSUE TITLE
Thread Album Download Breaking

### ISSUE THREAD

**Issue by Lunanite** [Floens/Clover#170]
Sometimes, when switching connections (phone network to Wi-Fi and vis versa), or losing connection for a short period (in a basement), when downloading a thread's images as an album, the download process freezes, and cannot be stopped by 'tapping to cancel' in the notification tray. The only fix for this has been force stopping Clover from Settings. This also causes blank/white images to be saved in the folder the images were being saved to.

**Comment by Floens** [comment]
I can't reproduce this. When I turn off the wifi when downloading all the tasks just quickly fail and tapping the notification clears it.
