### ISSUE TITLE
4chan links not opening in Clover

### ISSUE THREAD

**Issue by jacktheamiibo** [Floens/Clover#174]
NVIDIA Shield K1 user here.
In defaults, I have "Open supported links" set to "Open in this app" and under the "Supported links" tab has 4chan.org, www.4chan.org, and boards.4chan.org set.

**Comment by Floens** [comment]
What Android version?
How are you opening the link? I think clicking links from the browser stay in the browser, but external apps like chat apps will bring up the option to open in Clover.
