### ISSUE TITLE
Math tags on /sci/ doesn't load properly

### ISSUE THREAD

**Issue by KristianABR** [Floens/Clover#175]
Clover don't render the math tag at all. It can be pretty hard to read /sci/ if  there are some serious math

[math]\frac{10^{n+1}}{(n+1)!}=\frac{10^{n}}{(n)!}\frac{10}{n+1}[/math]

**Comment by Floens** [comment]
The math tags are processed with a client site javascript library on the site.
This is probably standard syntax, but it's too much work to properly parse this seen how small the usage will be.

**Comment by c933103** [comment]
Isn't it the standard TeX syntax?
