### ISSUE TITLE
Using some filters with double quotes will crash Clover

### ISSUE THREAD

**Issue by clownfishhuman** [Floens/Clover#181]
I noticed clover was crashing while trying to add the text "What you're referring to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux." to a filter. The crash happens when adding the second quotation mark at the end.

**Comment by jocfla** [comment]
By the way why don't we just say "GNU"? :^)

**Comment by Floens** [comment]
I can't reproduce this, are you on the newest version?
https://github.com/Floens/Clover/issues/101

**Comment by Floens** [comment]
nvm
