### ISSUE TITLE
Trimming long posts

### ISSUE THREAD

**Issue by galenasphaug** [Floens/Clover#182]
I noticed that while scrolling through the catalog,  posts are trimmed at a set amount of characters,  but not lines. This causes some words to be cut off,  and over all looks a bit strange. It might look a little better if you trimmed the post to about 15 lines.

**Comment by Floens** [comment]
I think the pr is good enough.
The card views have a dynamic height, so setting a max lines is not going to work.
Further, the card views use a faster version of the textview so maxlines does not work out of the box.
