### ISSUE TITLE
Use pass when reporting posts

### ISSUE THREAD

**Issue by lc-guy** [Floens/Clover#185]
I currently can't report using clover because my ISP is banned and I need a 4chan pass to do anything. 

The report dorm doesn't send pass data, so it asks for a captcha and then denies the report.

**Comment by Floens** [comment]
I don't want to create a native integration (like posting and deleting) because the form changes from time to time and this issue isn't that often.
That said, we can set the pass cookie on the webview when reporting.

**Comment by lc-guy** [comment]
I'm fine with the webview, personally.

**Comment by Floens** [comment]
Took longer than I would've liked. The backend of 4chan apparently doesn't show the captcha when the `pass_enabled` cookie is set, even when it's not 1, and deleting cookies sucks in Android (well, setting cookies in general).
