### ISSUE TITLE
Issue with saving images of the same name

### ISSUE THREAD

**Issue by jackwilko** [Floens/Clover#188]
Hi guys,

Noticed there's a problem with saving images with the same name multiple times, loads of people upload image.jpeg, annoying as hell.

I had a look and it looks like you could just remove the limit put in and it should be fine. 

Clover/app/src/main/java/org/floens/chan/core/saver/ImageSaver.java

/*
 *  Original 
 */
   private File findUnusedFileName(File start, boolean directory) {
        String base;
        String extension;

        if (directory) {
            base = start.getAbsolutePath();
            extension = null;
        } else {
            String[] splitted = start.getAbsolutePath().split("\\.(?=[^\\.]+$)");
            if (splitted.length == 2) {
                base = splitted[0];
                extension = "." + splitted[1];
            } else {
                base = splitted[0];
                extension = ".";
            }
        }

        File test;
        if (directory) {
            test = new File(base);
        } else {
            test = new File(base + extension);
        }

        int index = 0;
        int tries = 0;
        while (test.exists() && tries++ < 100) {
            if (directory) {
                test = new File(base + "_" + index);
            } else {
                test = new File(base + "_" + index + extension);
            }
            index++;
        }

        return test;
    }   

/*
 * Fix
 */

private File findUnusedFileName(File start, boolean directory) {
        String base;
        String extension;

        if (directory) {
            base = start.getAbsolutePath();
            extension = null;
        } else {
            String[] splitted = start.getAbsolutePath().split("\\.(?=[^\\.]+$)");
            if (splitted.length == 2) {
                base = splitted[0];
                extension = "." + splitted[1];
            } else {
                base = splitted[0];
                extension = ".";
            }
        }

        File test;
        if (directory) {
            test = new File(base);
        } else {
            test = new File(base + extension);
        }

        int index = 0;
        while (test.exists()) {
            if (directory) {
                test = new File(base + "_" + index);
            } else {
                test = new File(base + "_" + index + extension);
            }
            index++;
        }

        return test;
    }   

Also thanks for a great app to everybody who has worked on this :)

Ta,

Jack

**Comment by Floens** [comment]
You have 100 images named "image.jpg"?

**Comment by jackwilko** [comment]
yup :(
