### ISSUE TITLE
Can't delete boards on v2.1.3

### ISSUE THREAD

**Issue by ParadiseSeek** [Floens/Clover#189]
Not really an issue, but it's pretty annoying.

There are a bunch of boards I want to get rid off (an, ck, pol and etc.) but I can't really remove them for some reason. 

Android version: [Find at Settings > About phone > android version]
Phone model: [Find at Settings > About phone > Model number]
Clover version: [Find at the bottom of the settings screen of Clover]

**Comment by Floens** [comment]
Try swiping them away.

**Comment by ParadiseSeek** [comment]
Tried swiping them in all directions and it still doesn't work.

**Comment by Floens** [comment]
I can swipe a board away from the right to the left.
Please fill in your phone model and android version.

**Comment by ParadiseSeek** [comment]
Model number: LG-H631

Android version: 6.0

**Comment by Floens** [comment]
Are you sure you are swiping them away in the board editor?

**Comment by ParadiseSeek** [comment]
Yes.

**Comment by Floens** [comment]
Then I don't have a single clue, works fine here.

**Comment by ParadiseSeek** [comment]
Actually! It's alright, the swiping pattern in 2.0 is different than 1.0, but I got it now

Sorry for wasting your time, man.
