### ISSUE TITLE
App crashes when removing all boards and then starting the app

### ISSUE THREAD

**Issue by ConstruKction** [Floens/Clover#191]
The app crashes when trying to run it after removing all boards, then killing the app, and trying to open it up again.

Android version: 6.0.1 (Unofficial CM13)
Phone model: Xiaomi Mi 5
Clover version: 2.1.3

**Comment by Floens** [comment]
There was a check so that you can't remove the last board, but I forgot it when moving to ItemTouchHelper.
I'll add it in again, thanks.

**Comment by Floens** [comment]
Apparently there are two issues open about this
Closing as a duplicate of #282
