### ISSUE TITLE
Request: Bigger reply box

### ISSUE THREAD

**Issue by GODOG4** [Floens/Clover#196]
I've recent upgraded to 2.1.3 and while it runs smoothly and I think all the new features are great. There is one minor issue that has nearly ruined the entire app for me by virtue of making The experience of posting anything unbearable: the tiny reply Box. There seems to be no way to resize this box, and it makes writing any post longer than 200 characters physically painful.

Is there anyway I can switch to the full screen reply style. From before, or at least scale the current reply box? I really can't stand having to scroll through a 300 character post like I've written an essay.

**Comment by Floens** [comment]
A bigger reply screen is already on the trello, it's planned for the next release.

**Comment by Floens** [comment]
It now fills the available height, see #355
