### ISSUE TITLE
API parse error

### ISSUE THREAD

**Issue by Ockaie** [Floens/Clover#197]
API parse error

I'm receiving this error when I try to go to the following boards: /a/, /b/, /o/, /vg/. There could be more.
When I use the Chrome or Tor browser, I see nothing on these boards. Earlier today I also couldn't post on /b/, I kept getting Bad Gateway 502 on the site.

Android version: 6.0.1
Phone model: Nexus 5
Clover version: 2.1.3

**Comment by Floens** [comment]
The site is down, last reply was more than 3 hours ago.

**Comment by Ockaie** [comment]
You probably knew some idiot would write this.
