### ISSUE TITLE
WebM issues on some devices

### ISSUE THREAD

**Issue by floens** [Floens/Clover#2]
While Android claims to support WebM (http://developer.android.com/guide/appendix/media-formats.html#core) lots of devices will encounter playback issues.

Problems are:
No support at all: "Can't play this video". The message is generated by the default video player. Clover uses VideoView that is powered by the android video player. Playing the video in the browser / another app won't help.

On my Nexus 4 you can play WebM's, but after a while if you play a WebM (or any video) the device will crash. Input won't be handled and the screen will not refresh. Looking at the logs the system is still reacting to system events, but the screen is stuck. After a while the SystemUI will crash or the device will reboot.

These problems are probably caused with propretairy drivers for the GPU / or just GPU issues.

A workaround is to show the user an AlertDialog saying that webm support is crummy and it may or may not work on their device.

**Comment by ttsda** [comment]
This is happening to me on a Galaxy S2 running Cyanogenmod 11. I believe it is a problem with the hardware codec, as I have the same issue in mxplayer if I don't switch to S/W decoding.

**Comment by grrowl** [comment]
Enabling nuplayer in developer options fixed it for me, nexus 7 on android 5.0.2

**Comment by alex88** [comment]
With nuplayer it works fine but still it randomly becomes green an ui freezes

**Comment by nopjmp** [comment]
Looks like nuplayer is now the default as of 5.1 on my Nexus 7.

**Comment by detex1337** [comment]
Force GPU rendering + Disable HW overlays worked for me.

**Comment by floens** [comment]
In 2020, these issues are not common anymore, and we have ExoPlayer.
