### ISSUE TITLE
Request: Save tripcode across threads

### ISSUE THREAD

**Issue by Brownertbh** [Floens/Clover#201]
I'd like it if Clover saved my tripcode across threads.
Having to manually type in my name and trip in the name field every thread is annoying. 

Android version: 4.4.2
Phone model: LG-VS450PP
Clover version: 2.1.3
Thanks for Clover!

**Comment by Floens** [comment]
Could you not enter your trip in the "Default post name" setting?

**Comment by Brownertbh** [comment]
I thought that was only for names, i never knew it supported tripcodes.
