### ISSUE TITLE
Failed to show image

### ISSUE THREAD

**Issue by imset** [Floens/Clover#207]
My device is giving me a "failed to show image" error every time I press any image, webm, or gif.

My phone has always, without fail, run clover completely fine. This morning I decided to upgrade my version of CM to CM13, completely wiping my phone in the process.
Immediately I installed clover, and soon found I can't open any images at all. I can see the thumbnails and browse threads perfectly fine, but I can't open any images. I don't think that CM13 is the problem, since I have a friend with it that uses clover fine.
I have also already tried toggling HTTPS in the advanced settings.

Android version: 6.0.1, running Cyanogen Mod 13. This is NOT a custom rom, my phone came with CM installed (it's a OPO).
Phone model: Oneplus One, A0001
Clover version: Latest, 2.1.3.

Thanks for your time, I really love the app.

**Comment by imset** [comment]
Well this is embarassing. I solved my own problem I guess?
I tried reinstalling Google Play Services and it worked. So I guess if anyone is in my position in the future they can try that. I have no idea why that helped.

**Comment by Floens** [comment]
CM/OPO sets some weird APN proxy settings, that's the most common problem I noticed when some apps can't connect to the network. It could maybe be that GPS resets the APN settings to something correct.
