### ISSUE TITLE
Disk cache can exceed 60MB

### ISSUE THREAD

**Issue by tadev** [Floens/Clover#21]
The caching process of Clover is kind of strange, after opening the app and browsing through some boards and closing it, it has written 300+ of files to /sdcard/Android/data/org.floens.chan/cache/volley and filecache.
With a total size exceeding 60MB.

I suggest the use of RAM for caching, as the cached files are completely useless after opening the browser again some time after last using it, since most if not all of the images, thumbnails and threads are already gone. And even then, RAM is much faster than the sdcard. This could speed up clover quiete a bit.

**Comment by Floens** [comment]
Replaced the image loader with okhttp
