### ISSUE TITLE
Image gallery lag in nougat

### ISSUE THREAD

**Issue by Haunter** [Floens/Clover#220]
Gallery lag when swiping images. 

When in the image gallery and swiping from image to image it will hang up and lag, almost as if it was frozen. 

Android version: 7.0
Phone model: Nexus 6P
Clover version: 2.1.3

**Comment by Floens** [comment]
I'm seeing this behavior on Marshmallow too. It's when transitioning from the thumbnail to the ssiv. It didn't do this before.

**Comment by d9h02f** [comment]
Lagdroid strikes again!

**Comment by Floens** [comment]
I'm only seeing this when running in debug mode, the proper release version with proguard doesn't have this issue.
