### ISSUE TITLE
Question: When is the next release coming out?

### ISSUE THREAD

**Issue by trees12** [Floens/Clover#224]
Every day on /g/ someone makes a new thread asking when the next clover release is coming out. Is there any date set because a lot of people would like to know. Is there anything left to do before you can release the next version of f-droid?

**Comment by Floens** [comment]
There are a few high profile bug to fix, see the trello board. Other than that, it's ready to go.
I need to find some time to properly fix these issues. 
And yes you're right, the /g/ spamming is annoying and doesn't help a bit.

**Comment by emiliskvg** [comment]
Just a quick question. Will the next version be 2.1.4 or the version will stay the same? :)

**Comment by Floens** [comment]
Probably 2.2. Keeping the version number the same would defeat the purpose of it wouldn't it?

**Comment by emiliskvg** [comment]
Well yea :) Just wanted to make sure. I name my builds with your commit numbers for now. [Like this](https://i.imgur.com/gGSmZNb.jpg)

**Comment by andyklimczak** [comment]
>I name my builds with your commit numbers for now

@emiliskvg are you adding the hash by hand manually and building or did you edit clover to automatically find the latest commit hash?

because that's a really good idea I think

**Comment by emiliskvg** [comment]
> I name my builds with your commit numbers for now
> @emiliskvg are you adding the hash by hand manually and building or did you edit clover to automatically find the latest commit hash?
> 
> because that's a really good idea I think

Manually :disappointed:  .But I think that getting the latest hash from the GitHub API and auto including it is not that hard?
P.S: Lets say it does get the latest hash and adds it. That doesn't mean that it's running the latest committed build.(The last commit could've been months ago. (If that makes any sense to you, Havent slept for like 40 hours, English is failing me right now)).

**Comment by andyklimczak** [comment]
@Floens could you label the high profile bugs on trello, so that it's clear what needs to be done for next release?

**Comment by Floens** [comment]
I marked some cards

**Comment by inexist3nce** [comment]
I made an apk https://a.pomf.cat/mstnyv.apk

last commit d50508268e4fbb16af157b602fc8c07c9c2bb669
