### ISSUE TITLE
Random posts being hidden

### ISSUE THREAD

**Issue by The-idiots-Xgames721** [Floens/Clover#227]
Random posts being hiden

After posting in threads sometimes my own posts get hidden, I have many filters but none of them should be filtering any of my posts(none of them match the filter)

Android version: 5.1
Phone model: MOTO X
Clover version: 2.1.3

**Comment by Floens** [comment]
Please post your filters and the post this is about.

**Comment by The-idiots-Xgames721** [comment]
The post is long gone but if I remember it correctly it was "I know i was made to bring you back" in a thread about game quotes here are the filters 
http://m.imgur.com/vbrq9rp
http://m.imgur.com/wsO9Pmz

Sorry if it doesn't help much

I'll try to replicate it and if any posts get hidden again I'll get a screenshot from th Browser of said post

Thanks for the response by the way

**Comment by The-idiots-Xgames721** [comment]
http://m.imgur.com/UfgxDwl

Here are two of the hidden posts I dug out

**Comment by Floens** [comment]
The only logical conclusion is that your filters still get triggered some way, like when you have a filter for "foo" it will match "aafoobb" depending on the type you have set.

**Comment by The-idiots-Xgames721** [comment]
Ok thanks:)
