### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by Parinavshetty** [Floens/Clover#230]
Thumbnails load fine but images don't show

I tried toggling the use https button and tried restoring the phone also. Tried clearing the app data and reinstalling the app

This app used to work fine before never faced any issue before 

Android version: 5.1.1 LMY47V
Phone model: Redmi Note 3 snapdragon variant 
Clover version: 2.1.3

**Comment by Parinavshetty** [comment]
Well it started working when I tried to download the gallery so thanks anyway

**Comment by Floens** [comment]
Yeah these issues are very random an fix themselfs most of the time. Clover doesn't use any special way of downloading images, it uses OkHttp which a million other apps use.

**Comment by Parinavshetty** [comment]
Thanks man I really think you are one the best developers out there keep up
the good work

**Comment by hardliner5000** [comment]
Will there be a new release with the new fix soon?
