### ISSUE TITLE
How to get rid of the party hat?

### ISSUE THREAD

**Issue by DemetriussXVII** [Floens/Clover#233]
It's really annoying and I can't see anything because of it @Floens

**Comment by Phoexyael17** [comment]
@Floens at least make the hats much smaller. We can't see anything. On PC it comes off as nice because there's much more space between posts. Now we're facing a cluster fuck of purple and pink party hat on the left side of screen...

**Comment by Floens** [comment]
I'll make them smaller and only on the OP next time.
For now just change the date.
Happy birthday!

**Comment by DemetriussXVII** [comment]
@Floens  Thanks !

**Comment by beschoenen** [comment]
To what are those hats linked?

**Comment by Floens** [comment]
What do you mean?

**Comment by beschoenen** [comment]
When do the hats display, what's their trigger for displaying?

**Comment by Floens** [comment]
`ThreadListLayout#party/unParty`

**Comment by DemetriussXVII** [comment]
@beschoenen 4Chin's birthday

**Comment by DemetriussXVII** [comment]
@Floens Will we ever see a new update? Also do you have a tripcode?

**Comment by beschoenen** [comment]
@Floens @DemetriussXVII Thanks

**Comment by DemetriussXVII** [comment]
@beschoenen No problem.

**Comment by Floens** [comment]
Please refrain from posting so many massages - especially when unrelated to the issue - to an issue report, all watchers get an email for every message. @DemetriussXVII #224 and https://gist.github.com/Floens/20a796087159035d953a
