### ISSUE TITLE
Can't add new boards to Clover

### ISSUE THREAD

**Issue by 8569864** [Floens/Clover#234]
Can't add more boards to my clover 

Deleted Clover originally to try to fix an issue, but after installing the apk multiple times, I wasn't able to add any new boards. There would always be a message saying "The board with code __ does not exist." even if I used the right code.

Android version: 5.1.1
Phone model: LGLS675
Clover version: 2.1.3

**Comment by Floens** [comment]
The boards.json file loading was just broken by this change https://github.com/Floens/ChanTracking/commit/c86585ae0cc7664ebc1c5bef944b339152ddcbd3
I'll ask team 4chan kindly to maybe revert this change and I'll change Clover's behaviour.

**Comment by wearebots** [comment]
Has this issue been resolved?  I am still  experiencing this issue after a reinstall, reboot, etc.

**Comment by tommytom02** [comment]
Same issue here.  Can't add boards after having to refresh android and reinstall Clover.

**Comment by Floens** [comment]
Update to v2.2.0

**Comment by onodera-punpun** [comment]
f-droid still seems to list the old release.

**Comment by majurg** [comment]
@onodera-punpun f-droid v2.2.0 build is failing for some reason: https://f-droid.org/wiki/page/org.floens.chan/lastbuild_56

**Comment by tommytom02** [comment]
Was able to download from github and install manually.  Thanks Floens for the fix!  However, now I can't change the download directory to SD.  I've got a rooted GS4 running stock ROM 5.0.1.

**Comment by Floens** [comment]
Wait for f-droid to get the new build tools, shouldn't take too long.
The APK released here on github has a different signature than the one from f-droid, you can't interchangeably install them.
