### ISSUE TITLE
Low resolution icons (2.2.0)

### ISSUE THREAD

**Issue by beschoenen** [Floens/Clover#235]
![screenshot_20161003-215000](https://cloud.githubusercontent.com/assets/1887585/19051568/ba835664-89b3-11e6-8ba1-6d87fb56ab1d.png)

Icons are low resolution, icon in fab & icons in the menu bar.

(Display size set to large via Nougat's new setting, for this screenshot)

Android version: 7.0 (CM14)
Phone model: OnePlus 2
Clover version: 2.2.0

**Comment by Floens** [comment]
The build apparently decided to only spit out mdpi drawables or something. I'm looking into it.

**Comment by Floens** [comment]
Fixed.
