### ISSUE TITLE
Can't copy and paste stuff

### ISSUE THREAD

**Issue by DemetriussXVII** [Floens/Clover#237]
When I long press the screen the copy and paste pop up menu doesn't show up. It used to show up prior to 2.2.0

Android version: 6.0.1
Phone model: S7 edge international
Clover version: 2.2.0

**Comment by Floens** [comment]
Possible duplicate of #183

**Comment by DemetriussXVII** [comment]
@Floens I used to able to do it in Clover and I can do it in every app.

**Comment by DemetriussXVII** [comment]
@Floens Weird, I just tried it and it works. Gonna post updates later.
