### ISSUE TITLE
Open links in Chrome app 

### ISSUE THREAD

**Issue by bobo1724** [Floens/Clover#244]
Any way to default open in the Chrome app rather than the powered by Chrome minibrowser?

Tab S 10.5 
Android 5.0.1
Clover 2.2.0

**Comment by Floens** [comment]
The menu in the top right has an option to open the tab in Chrome. There is no option to always open in a browser right now.

**Comment by bobo1724** [comment]
Was this removed from the previous version of Clover? If so, any reason?

**Comment by Floens** [comment]
Clover uses Chrome custom tabs now, see https://developer.chrome.com/multidevice/android/customtabs
Previous versions just opened the browser.

**Comment by bobo1724** [comment]
Got it thanks!
