### ISSUE TITLE
4chan added /vip/ and clover doesn't recognize it.

### ISSUE THREAD

**Issue by remeranAuthor** [Floens/Clover#246]
New (trial) board. http://boards.4chan.org/vip/ for 4chan Pass Users Only. I don't know if there'll be extra nonsense like /qst/ that you need to account for but good luck.

**Comment by Floens** [comment]
It does support it, but you'll have to update to v2.2.0.
You didn't fill in the form, are you on that version?

**Comment by remeranAuthor** [comment]
Oh, I'm sorry. I thought I was on the newest version but I see that F-Droid doesn't seem to have v2.2.0 yet. Or at least it isn't showing up on my phone.

Sorry for wasting your time and thank you!

**Comment by Floens** [comment]
Refresh the fdroid repo and it should show up.
