### ISSUE TITLE
Can't add /pol/

### ISSUE THREAD

**Issue by nickcorona** [Floens/Clover#247]
Can't add /pol/ as a board

Try to add pol

Android version: 6.01
Phone model: nexus 6
Clover version: 2.20

**Comment by Floens** [comment]
Are you sure it's not #234 ?
And all boards are added by default in v2.2.0

**Comment by Ockaie** [comment]
What happens when you do?

**Comment by d9h02f** [comment]
It's not a bug, it's a feature!
