### ISSUE TITLE
Download notification stays up if all files were already downloaded

### ISSUE THREAD

**Issue by Floens** [Floens/Clover#250]
Download notification stays up if all files were already downloaded.

The notification should be properly removed even if the queue is empty.

Steps to reproduce:
1) Download some thread
2) Wait for the notification to disappear
3) Download the same thread again
4) The notification is stuck

Android version: 7.0
Phone model: Nexus 5X
Clover version: v2.2.0

**Comment by IzaacSETEC** [comment]
This is a legit issue. An attempt to "download album" once will run to completion. Subsequent attempts will count to the number of new images and then stop.

Prior version behavior was to quickly leap to the number previously downloaded and then run to natural completion.

**Comment by hardliner5000** [comment]
Same troubleshoot.
