### ISSUE TITLE
Suggestion: Add a option to view threads in 1 column view in catalog mode (like a list)

### ISSUE THREAD

**Issue by fuaxio** [Floens/Clover#256]

**Comment by Floens** [comment]
Why not use the board view for this?

**Comment by fuaxio** [comment]
yeah but it has replies along with the op posts . I would like to view only the op posts. 
if there would be an option to view in 1 column mode it would be great.
![screenshot_2016-11-02-17-42-16](https://cloud.githubusercontent.com/assets/13122476/19928423/633d1f92-a124-11e6-9e77-9e350eb15ac5.png)

**Comment by fuaxio** [comment]
haha excuse me for my autism
