### ISSUE TITLE
Auto-mute WEBM Setting

### ISSUE THREAD

**Issue by lehitoskin** [Floens/Clover#260]
I looked around Clover's settings and didn't find one so... feature request: A setting in Clover that makes sure webm playback is always muted. On the rare occasion that I find a webm that has audio, I would prefer it does not blast out of my phone's speakers late at night, waking my room mates. 4chan has a setting to un-mute webm playback, meaning they're muted by default and having the Android app reflect that would be very nice.

**Comment by galenasphaug** [comment]
This feature has been added in the latest dev build.

**Comment by Floens** [comment]
We can close this if we also make a setting for the default mute state.

**Comment by Floens** [comment]
https://github.com/Floens/Clover/commit/272f02258a8f5a5e887131c9de3d254f4e8d8599
