### ISSUE TITLE
Crash and restart my phone

### ISSUE THREAD

**Issue by xrxrxr** [Floens/Clover#266]
Hello i have an 
Xiaomi hongmi 1s 
With Android 7.1.1 cynaogen based called mokee ROM
I installed Clover from fdroid 
And everytime i try tout watch à vidéo of 4chan 
It restart my phone si i putted play on external player and i just crash the app

**Comment by Floens** [comment]
Custom roms usually don't implement webm playing well, see #2 
The external media player is a known bug
