### ISSUE TITLE
Can't open URL's surrounded by braces

### ISSUE THREAD

**Issue by JaschaKauth** [Floens/Clover#278]
detailed explanation of the issue]
If there is a URL surrounded with braces, it can not be opened in a browser.
Example:
(https://google.com)
If I click this URL, clover asks me 'Open link'. If I now click OK, I get the message 'No applications found to open link'.

[steps to reproduce the issue]
Write a new post, that contains a link surrounded by braces. Click that link. 

Android version: 6.0.1
Phone model: A0001 (Oneplus One)
Clover version: v2.2.0

**Comment by Floens** [comment]
Yes, braces need to be skipped in the cruel link detection system we have now, just like `>` is skipped. I'm not sure if the brace at the end needs to always be skipped, only when the url starts with a brace, or not at all.
