### ISSUE TITLE
Ability to Share Links in Post

### ISSUE THREAD

**Issue by kamegami13** [Floens/Clover#279]
Best I can tell, there is currently no way to directly Share a link in a post. I have to open the link in a browser then Share it. I use Share frequently for bookmarking so this is cumbersome, especially for links that require logins or contain mobile redirects. The ability to long press a link and get a Share option would be ideal.

Clover version: 2.2.0

**Comment by Floens** [comment]
You can use selection (on dev) to copy the link.
