### ISSUE TITLE
Closing a.webm vs gif problem

### ISSUE THREAD

**Issue by casedizzy** [Floens/Clover#280]
When playing a .webm in 1.2.11, you could tap on the screen (anywhere on the .webm) and it would close/collapse the .webm.

In 2.2.0, tapping the .webm only brings up default player controls, and the .webm will stay on loop unless you press the back key (on phone or the back arrow in clover). .gifs are behaving normally, and tapping on it -closes it.

To replicate problem: Open a webm on any board, tap it on the screen/video, and it doesn't close. Open a.gif, tap on it, it closes. 
Repeat in 1.2.11, webms will close by tapping the webm, as will gifs

System version: Stock, non-rooted 6.0.1
Phone model: Samsung SM-G935A, Galaxy S7, at&t.
Clover version: 2.2.0, I am using the clover stock media player.

**Comment by Floens** [comment]
This is intended behaviour, webm's show controls when tapping, instead of going back to the thread.
