### ISSUE TITLE
Removing all the boards from your list will brick the app

### ISSUE THREAD

**Issue by DankParrot** [Floens/Clover#282]
[short and descriptive title]
If you delete every board from the board list, clover will die.
[detailed explanation of the issue]
The app will always fail to start whenever there are no boards saved, meaning you need to reinstall to use it again.
[steps to reproduce the issue]
1. Launch clover
2. Go to the board edit page
3. Remove every single board
4. Quit clover
5. It will no longer boot after that without reinstalling
Android version: 7.1
Phone model: Google Pixel XL
Clover version: 2.2.0

**Comment by andyklimczak** [comment]
Can confirm it crashes on `dev` branch.
On the `multisite` branch, it doesn't crash but hangs on 'Fetching boards'

Maybe the app should stop the user from deleting the last board (so there is always one to load)?

**Comment by Floens** [comment]
Yes, you shouldn't be able to remove the last board on dev, but multisite should handle it just fine. Just another thing on the todo list.

**Comment by Floens** [comment]
Fixed in multisite, which was just merged to dev. Not applicable anymore.
