### ISSUE TITLE
Pinned menu gesture too narrow

### ISSUE THREAD

**Issue by MisakaImoutoWaifu** [Floens/Clover#29]
I've noticed while using material design apps with a similar setup that it's very easy to pull off the gesture despite having a case on my phone, while on clover is nearly impossible.
Google Play is a great example to check out.
It would be very useful if the gesture was more forgiving or even adjustable for those of us who have cases or bumpers.

**Comment by Floens** [comment]
Now using Google's newest drawer implementation, should be all good!
