### ISSUE TITLE
Thread making not possible with captcha v1

### ISSUE THREAD

**Issue by phunkism** [Floens/Clover#291]
Cannot make threads anymore with clover. They disabled thread making with legacy captcha, could you implement picture captcha?

**Comment by Floens** [comment]
Clover supports both captchas. Switch them in the advanced settings. Go there by first going to the settings, and then tapping the menu icon at the top right. Turn on "Use the new captcha".

**Comment by andyklimczak** [comment]
Should we now switch it to picture captcha by default?

**Comment by Floens** [comment]
I don't know. I don't know why it was disabled for threads, if that was intentionally, and if it stays like this.
@desuwa do you know?
Otherwise we can force a picture captcha on thread making, but if it gets reversed later we'll get complains about that again.

**Comment by desuwa** [comment]
It will stay like this. Recaptcha v1 was never really supported for thread creation, which uses the default posting form.

**Comment by Floens** [comment]
Thanks for the update.
We'll force the v2 captcha for thread creation then.
Time for a new release soon, I'll make some time for it so I can fix #250 and #239 and fix this issue.

**Comment by phunkism** [comment]
Thanks guys, yeah i switched from legacy captcha to picture captcha and i can make threads again

Ps:you can normally post with legacy captcha but you cant make threads
