### ISSUE TITLE
HTTPS error, can't add boards

### ISSUE THREAD

**Issue by eisevh** [Floens/Clover#293]
I can't add any boards when I install clover

I downloaded the APK from your site, but it gives me an HTTPS error, and as a result, I can't add any boards. 

I'm running android version 5.0.1 on a Samsung Galaxy S4
Clover v2.2.0

**Comment by Floens** [comment]
You didn't fill in the template, why? Your Clover version is important.

**Comment by eisevh** [comment]
Oh sorry. It's v2.2.0, which I believe is the newest version

**Comment by Floens** [comment]
Not applicable with the new flow.
