### ISSUE TITLE
Webm player on Android Nougat

### ISSUE THREAD

**Issue by Camranbant** [Floens/Clover#296]
Since updating to nougat, webms won't play. If using the inline player, a blank webm loads and the app will stop updating. If using the external player in the settings, the app force closes. 

This happens when opening any webm 

Android version: 7.0
Phone model: SM-G935F 
Clover version: v2.2.0

EDIT: Not sure what happened but after switching between inline and external a few times the problem has stopped.

**Comment by Floens** [comment]
Thanks for the info. This is related to #2 although there should never be a crash if you enable the external media player mode.

**Comment by Camranbant** [comment]
Oh,  I had tried the "Force GPU rendering" and "Disable HW overlays" options and neither made any difference.

**Comment by RaynebowDeathtrap** [comment]
Same here. I'm on Android Nougat using Samsung Galaxy Note 5. Just updated

**Comment by Floens** [comment]
Webms not working with the internal player is the eternal issue #2 
The external one not working is #310
