### ISSUE TITLE
Request: flag collector

### ISSUE THREAD

**Issue by simplypro** [Floens/Clover#298]
[short and descriptive title]

[detailed explanation of the issue]

[steps to reproduce the issue]

Android version: [Find at Settings > About phone > android version]
Phone model: [Find at Settings > About phone > Model number]
Clover version: [Find at the bottom of the settings screen of Clover]

**Comment by Floens** [comment]
You probably meant something like the flag collector script (two words aren't that descriptive).
That is an external script not from 4chan and is too much work to maintain.
