### ISSUE TITLE
[Request] Notification Options

### ISSUE THREAD

**Issue by zero77** [Floens/Clover#299]
Can you add the option to show notifications only when someone posts in a saved thread.
Thanks

**Comment by Floens** [comment]
Isn't that the way it is now? You only get notifications of threads that you bookmarked.

**Comment by zero77** [comment]
Sorry I didn’t really specify, what I mean is an external notification in the dropdown menu like when you receive a text or a message on signal.

**Comment by andyklimczak** [comment]
By drop down menu I think you mean push notifications.

Clover supports push notifications. Make sure you have ```Watcher Settings``` enabled. (⚙️ symbol next to Bookmark Threads in left side drawer)

**Comment by zero77** [comment]
Thanks @andyklimczak that’s the sort of thing I mean but something that is not constancy there and a separate push notification for each thread showing the number of new photos and comments.
Like github.com/grzegorznittner/chanu has.

**Comment by Floens** [comment]
I think I deciphered your request. You want a separate notification for each watching thread. So when you watch three threads, I'll show three notifications.
This was against the Android guidelines, and then not, and now you have channels. We might separate them again.

**Comment by zero77** [comment]
Yes, this request was unintentionally rather cryptic.
Yes exactly, a separate notification for each watched thread and notifications that aren’t constantly there like the current one.
It would be excellent if you could implement this, as the current notification is irritating and not very informative.
Thanks

**Comment by Floens** [comment]
The persisting notification is to not let the Clover process be killed, and this will probably be needed with Android O.
Just so you know, the notification does change.

**Comment by zero77** [comment]
Well if it is needed for some versions but not others could you add an option to disable it, when you get a chance to look at this. Yes, I have seen it change but I think a more specific one would be better, showing the number of new photos and comments, instead of the comment its self.

**Comment by Floens** [comment]
The notification is going away with the O targeting, closing this issue for that.
