### ISSUE TITLE
Reveal image spoilers don't work

### ISSUE THREAD

**Issue by codecodingcode** [Floens/Clover#300]
Reveal image spoilers don't work.

"Reveal image spoilers" is enabled (Advanced settings) but image spoilers are still visible. "Reveal text spoilers" works fine.

Android version: 6.0.1
Phone model: Moto G4 Plus
Clover version: v2.3.0 (GitHub, clean install)

**Comment by Floens** [comment]
Regression confirmed, setting does nothing for me. I must've broken it.
