### ISSUE TITLE
/cock/ is a board now. 

### ISSUE THREAD

**Issue by QuakersOat** [Floens/Clover#301]
[short and descriptive title]

[detailed explanation of the issue]

[steps to reproduce the issue]

Android version: [Find at Settings > About phone > android version]
Phone model: [Find at Settings > About phone > Model number]
Clover version: [Find at the bottom of the settings screen of Clover]

**Comment by Floens** [comment]
Email 4chan to add it to `https://a.4cdn.org/boards.json`

**Comment by QuakersOat** [comment]
Done.
