### ISSUE TITLE
Error posting

### ISSUE THREAD

**Issue by phunkism** [Floens/Clover#305]
Getting "error posting" since 2 days ago

Cannot post threads nor reply to anything, ne er had this problem before

Android version: 6.0.1
Phone model: SM-A500FU
Clover version: 2.3.0 F droid

**Comment by Floens** [comment]
Can you try the two different captcha implementations? You can change the captcha used at the settings screen, menu, advanced settings, and toggling the switch for captcha.
Can you also try different networks, wifi and lte?

**Comment by phunkism** [comment]
Woah, it works with my neighbors wifi....any idea why its not working on mine?

**Comment by Floens** [comment]
Could be a lot of things, blockage, routing issues, a ban, etc.

**Comment by phunkism** [comment]
But it works when i open 4chan im chrome but not on clover hmm..

**Comment by Floens** [comment]
I don't think I can fix this because it could be so many things. Clover uses okhttp for posting network communication, which is the most used http library for android today.
