### ISSUE TITLE
Will the new board bant be added?

### ISSUE THREAD

**Issue by The-idiots-Xgames721** [Floens/Clover#313]
[short and descriptive title]

[detailed explanation of the issue]

[steps to reproduce the issue]

Android version: [Find at Settings > About phone > android version]
Phone model: [Find at Settings > About phone > Model number]
Clover version: [Find at the bottom of the settings screen of Clover]

**Comment by andyklimczak** [comment]
Already is. If it's not, just add through the settings `bant`

**Comment by Floens** [comment]
Please fill in the provided template.
