### ISSUE TITLE
[REQUEST] Anyway to edit the thread update timer?

### ISSUE THREAD

**Issue by seg09** [Floens/Clover#314]
I'd like to adjust the update timer at the bottom of the thread, the "Loading in 14...", "Loading in 50...", etc, to a specific number of seconds. Is there anyway to do this? The timer increasing at intervals is a bit of an inconvenience to me, and I couldn't find an option to customize it to a constant 5 or so seconds. Thank you!

Android version: 6.01
Phone model: SAMSUNG-SM-J320AZ
Clover version: v2.3.0 F-Droid

**Comment by Floens** [comment]
4chan requests not hitting their servers so often. I recreated what the site itself does, with an increasing interval that resets when there are new posts.

**Comment by seg09** [comment]
Thank you. Is there a way to remove the increasing interval, and keep the refresh timer at a custom number of seconds?

**Comment by Floens** [comment]
No.
