### ISSUE TITLE
New ReCaptcha android API support 

### ISSUE THREAD

**Issue by nar001** [Floens/Clover#317]
Since they just introduced it, will you implement it in your app? https://android-developers.googleblog.com/2017/06/making-internet-safer-and-faster.html

**Comment by Floens** [comment]
Yeah I saw, will implement this, alongside the web versions for v2 and v1.

**Comment by nar001** [comment]
Nice, thanks!

**Comment by Floens** [comment]
I looked into this a bit, and it isn't just pluggable in the current site key structure of 4chan.
4chan would need to integrate another site key specially for Clover, and I doubt that is going to happen.
And we need to integrate with Google Play Services, as expected, and that takes some time, to filter it out for f-droid etc.

**Comment by nar001** [comment]
Oh, that's too bad then, thanks for looking into it though!
