### ISSUE TITLE
Request: Make post text selectable with long press

### ISSUE THREAD

**Issue by cecpog** [Floens/Clover#324]
This would make citing parts of other replies much easier. Currently, your only option is to quote the entire post and manually delete the parts you don't need.

**Comment by Floens** [comment]
I worked on this a bit but it requires a lot of work with the custom postcell movementmethod, so I haven't finished it yet.

**Comment by OpenUp596** [comment]
This is an essential feature since you usually have to google a lot of stuff.

**Comment by Floens** [comment]
Was added on dev some time ago.
