### ISSUE TITLE
Support for new flags

### ISSUE THREAD

**Issue by WeWuzKangz** [Floens/Clover#328]
Please add support for the new flags on /pol
Android version: 7.1.2
Phone model: Nexus 5 
Clover version: 2.3.0

**Comment by rogerlopz** [comment]
Its already implemented, check 6724905b059e892f116e311560c9071b1d1dfa04
We just need to wait for the f-droid update or you can just compile the .apk from source.

**Comment by andyklimczak** [comment]
@Floens just wondering, is there any reason you're waiting on releasing 2.3.1 with the flags update?

**Comment by Floens** [comment]
Sorry, I've been busy.
I was testing the release so far and have since not had time to release it. It's ready for release, I just need to change the versions and release the APK. F-Droid will follow after that (that can take up to a week, their situation is a bit hectic).

**Comment by andyklimczak** [comment]
no worries, just seeing if there is anything we can help with

**Comment by andyklimczak** [comment]
not that it matters too much, but are we missing the flag update in the release notes?

**Comment by Floens** [comment]
I thought it was too insignificant.

**Comment by unalignedcoder** [comment]
I have 2.3.1. How can I change the flag?
