### ISSUE TITLE
Request: iOS release

### ISSUE THREAD

**Issue by annoyinggiraffe** [Floens/Clover#331]
I recently bought an iPhone to replace my Galaxy S2. While I was setting up my new phone, I checked the appstore to see if there were any 4chan clients. Only one of them is half decent, and it's called The Chan. I bought the app, and it is terrible. Download the app yourself, and you'll see what I mean. It's not even close to Clover in terms of app quality and usability. Everything in that app is horrendous.

Android version: iOS 10.3.2 (can't jailbreak this, so Fortune is out of the question)
Phone model: iPhone 6 Plus
Clover version: I wish

floens plz

**Comment by Floens** [comment]
haha no

**Comment by Floens** [comment]
Clarification: this app is build on the normal android framework, and not on some sort of cross-platform framework. That, and things like the common iOS navigation patterns aren't supported. There is no porting, only a complete write from the ground up.

For iOS, look at the Fortune app on Cydia. That "the chan" app is just a wrapper around the site.

**Comment by annoyinggiraffe** [comment]
Ok thanks. I'll wait for a jailbreak for my version, and check out Fortune. :)

**Comment by acedened** [comment]
@annoyinggiraffe, hi! I’m the developer of The Chan. Could you please explain why it is terrible? I really appreciate any feedback.

**Comment by Floens** [comment]
Sorry, I have confused the app with another one which was a web wrapper.
