### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by floppyD** [Floens/Clover#337]
Many lines with "Script error" appears, only when using the new captcha. They usually increase after posting.
http://imgur.com/a/gdZHy

6.0
Moto G3
Clover 2.3.1 F-Droid

**Comment by Floens** [comment]
This actually isn't an issue. The captcha page is programmed to output all `window.onerror` calls to the screen, but if it works then it's ok.
The captcha page is now loaded each time it's needed, instead of keeping the page cached. The error won't be visible anymore.
