### ISSUE TITLE
[Request] To be able to see what current post number is

### ISSUE THREAD

**Issue by WeWuzKangz** [Floens/Clover#339]
To be able to see how long until next the next GET is. That way clover users could have an advantage for rolling trips, quads etc. xDxD
Android version: 7.1.2
Phone model: Nexus 5
Clover version: 2.3.1

**Comment by Floens** [comment]
What? the post number is there.

**Comment by WeWuzKangz** [comment]
I think you misunderstood what I meant. To be able to view what the current post number is before you post so you can try and time it just right to get either dubs, trips etc. You would basically have to call the 4chan api, request current post number and then a random post from page 10, with those 2 determine how long it's been and then determine posts per second average to calculate when next trips, quads etc would be

**Comment by Floens** [comment]
Hm ok, but that's way out of scope for clover. Plus, GETs are against the rules.
