### ISSUE TITLE
The board code a is unknown

### ISSUE THREAD

**Issue by c933103** [Floens/Clover#342]
Tried to add 4chan boards, but shown as unable to add
Steps to reproduce:
1.  Download,install, and then launch the app in offline environment
2. Try to add boards like a, fail, resume internet connectivity , try again, still fail

Android version: 5.1
Phone model: Lenovo Tab 2 A8-50F
Clover version: v2.3.1-FDroid

**Comment by Floens** [comment]
This has been occurring randomly (there are a few issues for this already) but I've never been able to reproduce it.
People have had success restarting Clover and then trying it again.
