### ISSUE TITLE
How do I change the theme? 

### ISSUE THREAD

**Issue by danny12beje** [Floens/Clover#343]
[short and descriptive title]
Kinda self-explanatory 
[detailed explanation of the issue]

[steps to reproduce the issue]

Android version: [Find at Settings > About phone > android version]
Phone model: [Find at Settings > About phone > Model number]
Clover version: [Find at the bottom of the settings screen of Clover]

**Comment by Sietsem** [comment]
Closing this because it's not an issue with Clover. The theme can be changed in Settings -> Themes.
