### ISSUE TITLE
Unable to post.

### ISSUE THREAD

**Issue by mitchmat518** [Floens/Clover#347]
I'm getting an indefinite loading circle any time I try to post. I tried both types of captcha, along with using a 4chan pass but I still can't get anything to post. Uninstalling and reinstalling Clover fixed the problem for a few hours, but is now back to not posting.

Android version: 7.0
Phone model: XT1585
Clover version: 2.3.1 F-Droid

**Comment by mitchmat518** [comment]
Also worth mentioning I have tried it on multiple wifi networks along with cellular data

**Comment by Floens** [comment]
This usually goes away.
Please reopen if this is still an issue.
