### ISSUE TITLE
Image upload source is locked

### ISSUE THREAD

**Issue by boardfish** [Floens/Clover#349]
The source you choose when uploading an image cannot be changed again after selecting 'Remember my choice'

When uploading an image, you're able to choose a source app. However, selecting 'Remember my choice' means that even uninstalling the app does not allow you to change which app you chose. 

Upload an image to accompany a post, and select 'Remember my choice' when choosing which app to use. 

Android version: 7.0 NRD90M
Phone model: Redmi Note 4 Global
Clover version: v2.3.1 F-Droid

**Comment by Floens** [comment]
This is normal Android behaviour, as far as I know.
When you tell the picker to use an app as default, it will automatically open that app.
If you want to clear a default, you go the app from the settings, and tap the clear defaults button.

Also, in never versions of Android the Open from system screen should open, but I guess that redmi has changed that behaviour back to the more confusing intent picker.

**Comment by boardfish** [comment]
Ah, my bad. I thought that you'd have to clear the default in the settings for Clover and not whatever else. Thanks. On 19 Aug 2017 15:45, Florens <notifications@github.com> wrote:This is normal Android behaviour, as far as I know.
When you tell the picker to use an app as default, it will automatically open that app.
If you want to clear a default, you go the app from the settings, and tap the clear defaults button.
Also, in never versions of Android the Open from system screen should open, but I guess that redmi has changed that behaviour back to the more confusing intent picker.
