### ISSUE TITLE
Crash while browsing /g/62451753

### ISSUE THREAD

**Issue by nonijod** [Floens/Clover#357]
Crash while browsing /g/62451753

Clover crashes while browsing /g/62451753 roughly in the middle of the thread, most likely because of >>62454874. Happens every time even after restart.
E/AndroidRuntime(28966): FATAL EXCEPTION: Thread-1227
E/AndroidRuntime(28966): Process: org.floens.chan, PID: 28966
E/AndroidRuntime(28966): java.lang.IllegalArgumentException: width and height must be > 0
E/AndroidRuntime(28966): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:815)
E/AndroidRuntime(28966): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
E/AndroidRuntime(28966): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:726)
E/AndroidRuntime(28966): 	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:602)
E/AndroidRuntime(28966): 	at com.a.a.b.v.b(ImageRequest.java:169)
E/AndroidRuntime(28966): 	at com.a.a.b.v.a(ImageRequest.java:126)
E/AndroidRuntime(28966): 	at com.a.a.d.run(CacheDispatcher.java:118)

Android version: 4.4.2
Phone model: Lenovo A536
Clover version: v2.3.1 F-Droid

**Comment by Floens** [comment]
Thank you for the trace, I added a check for the sizes.
