### ISSUE TITLE
Disabling animations causes an input loop on Android O, hanging the app.

### ISSUE THREAD

**Issue by Fairhill** [Floens/Clover#360]
[short and descriptive title]
Crashing after couple minutes on Android O
[detailed explanation of the issue]
App freezes and has to be force closed - only thing that responds is the back button.
[steps to reproduce the issue]
Open clover, browse for 2-3 mins
Android version: [Find at Settings > About phone > android version] 8.0.0
Phone model: [Find at Settings > About phone > Model number] Nexus 5x
Clover version: [Find at the bottom of the settings screen of Clover]
2.3.1

**Comment by Floens** [comment]
I cannot reproduce this.
Were you running with power saver on perhaps?

**Comment by Fairhill** [comment]
Nope, tried with it both on and off. Any ideas?

**Comment by Floens** [comment]
You can look at the crash logs.
Go to the settings. At the about section, tap "Clover" five times. Next, go to the developer settings at the bottom. Then, tap view logs, and look at the relevant crash at the bottom. You can also paste the logs here with the menu option.

**Comment by Fairhill** [comment]
So turns out the app itself does not crash - the screen freezes. Noticed this because as it "crashed" the thread continued automatically refreshing. 

No crash log then.

Again, only thing that works is pressing the physical back button - it will take me to the previous screen but it is still frozen.

Any ideas?

**Comment by Floens** [comment]
This looks like a revivement of https://github.com/Floens/Clover/commit/262f34dfc11287819daed5bb3edb5ed72c0a1b73 then

**Comment by Floens** [comment]
I can reproduce this when I turn on battery saver, in other words, the animations are disabled. Do you always have animations disabled?

**Comment by Fairhill** [comment]
Ah yes, I do, forgot about that. Never had a problem with it before.

**Comment by Floens** [comment]
Thanks, good to know!
