### ISSUE TITLE
Save image with original filename setting isn't working

### ISSUE THREAD

**Issue by gut5** [Floens/Clover#368]
[short and descriptive title]

[detailed explanation of the issue]
The board filename is what the image is saved as
[steps to reproduce the issue]

Android version: [Find at Settings > About phone > android version]
7.1.1
Phone model: [Find at Settings > About phone > Model number]
Clover version: [Find at the bottom of the settings screen of Clover]
2.3.1

**Comment by Floens** [comment]
The board filename, sorry?

**Comment by gut5** [comment]
The filename that isn't the original one, the "other" one.

**Comment by Floens** [comment]
It's the other way around. The original filename the setting describes is the filename 4chan assigns, the timestamp. The non original name is the filename the user uploaded the image is.

It's confusing, and should be changed.
