### ISSUE TITLE
app having "network error" over wifi

### ISSUE THREAD

**Issue by flashmasterfive** [Floens/Clover#371]
My app has been acting up, not working on wifi.

When I boot up the app using Wifi, it can't load anything and it says "Network error", yet when i load it using LTE (data) it works perfectly ? It just started doing this 3 days ago, and for no apparent reason.

I have no clue on how to reproduce the issue, it came on it's own.

Android version: 7.1.2
Phone model: Samsung SM-G900F
Clover version: Clover 2.3.1 

Thanks !

**Comment by Floens** [comment]
This sometimes happens without any apparent reason, I haven't had the issue myself. Clover uses the normal http libraries, without any tricks. So I don't know how to solve this.

**Comment by flashmasterfive** [comment]
do you think that reinstalling the app would fix it ? if could avoid that 'd be great, but if i have to, i will.
