### ISSUE TITLE
Feature: new posts count in the pinned posts field

### ISSUE THREAD

**Issue by OpenUp596** [Floens/Clover#376]
To check if there are any new posts you have to go through each pinned thread manually. Instead there could be a little number right to the thread title or inside the thread's image container.

![sketch-1514114155215](https://user-images.githubusercontent.com/33358726/34326046-ae768432-e8ac-11e7-8f20-c5caee6706fc.png)

**Comment by Floens** [comment]
Enable the thread watcher.

**Comment by OpenUp596** [comment]
Thank you, sorry I didn't know about this feature.
