### ISSUE TITLE
[Request] - Backup/Restore Clover settings/config

### ISSUE THREAD

**Issue by bearstampede** [Floens/Clover#379]
I find myself re-installing Clover fairly frequently (have been an avid user for years), and being able to restore all my settings (especially things like filters and boards) would be super awesome. I looked through open issues but couldn't find anything similar to this request. Are these settings/configurations stored in such a way to make backup/restore a realistic option?

Android version: 8.0.0
Phone model: Nexus 5x
Clover version: 2.3.1

**Comment by andyklimczak** [comment]
Just wondering, why are you reinstalling so often?

**Comment by Floens** [comment]
The data directory is saved by google, so reinstalling the app should restore all settings and content.
