### ISSUE TITLE
Dark and Black themes not working

### ISSUE THREAD

**Issue by fishstik** [Floens/Clover#38]
Changing theme to Dark or Black makes background, action bar, and text in Settings all white. Changing to Black makes action bar white everywhere in the app. Screenshots below.

Settings - Light (normal behavior): http://i.imgur.com/XygChpr.png
Settings - Dark (text and bg is white): http://i.imgur.com/Bun3bnN.png
Settings - Black (text, bg, and action bar are white): http://i.imgur.com/FxXoeam.png
Main - Black (action bar is white): http://i.imgur.com/N4tqxCc.png

**Comment by nopjmp** [comment]
Your custom rom is probably overriding the settings even when "Dark Mode" is turned off to force it to be light. I have never experienced that problem with CyanogenMod on the 4.4.x series so they may be using custom code to do the dark mode.

**Comment by Floens** [comment]
This is fixed.
