### ISSUE TITLE
Crashes when quoting someone

### ISSUE THREAD

**Issue by galenasphaug** [Floens/Clover#384]
[detailed explanation of the issue]
Clover exits when quoting people, but not when quoting text.
[steps to reproduce the issue]
Quote any post
Android version: 7.1.1
Phone model: OnePlus 5T
Clover version: 2.3.1 4a9b0b42

**Comment by Floens** [comment]
Oh sorry, I fixed this but haven't pushed it yet.
As I said in the thread, expect a polished alpha built by me in the next few days.

**Comment by Floens** [comment]
Fixed with https://github.com/Floens/Clover/commit/fbe777d0cd68314a5ef2458a8dd0da65494c3bed
