### ISSUE TITLE
Clover crashes on pressing Report

### ISSUE THREAD

**Issue by hardliner5000** [Floens/Clover#387]
Clover crashes systematically when pressing to report. Thats the whole issue.
Android version: 4.3 (very old device)
Phone model: LT30p Sony Xperia 
Clover version: 2.3.1

Thanks

**Comment by Floens** [comment]
The report button is only for apps installed from the play store. As such, it doesn't work. (It shouldn't even display, but that's probably an old Android bug.)

Clover doesn't have proper built-in crash reporting yet. The best you can do is submitting a crash log.

Tap the version in the settings a few times, go to the developer settings and then view logs.

**Comment by hardliner5000** [comment]
Thanks a lot Floens.

Here's the requested Crash log:

--------- beginning of /dev/log/system
D/webcoreglue: netstack: Memory Cache feature is ON
D/HostStatisticManager: netstack: DNS Host Prioritization is: ON, Version: 5.0.1
I/        : netstack: LIB_MGR - Lib loaded: libdnshostprio.so
I/        : netstack: STAT_HUB - Succeeded to load plugin: libdnshostprio.so
E/        : netstack: LIB_MGR - Error loading lib spl_proc_plugin.so
E/        : netstack: STAT_HUB - Failed to load plugin: spl_proc_plugin.so
I/        : netstack: LIB_MGR - Lib loaded: pp_proc_plugin.so
I/        : netstack: STAT_HUB - Succeeded to load plugin: pp_proc_plugin.so
E/        : netstack:  STAT_HUB - App org.floens.chan isn't supported
D/        : external/chromium/net/socket/tcp_fin_aggregation_factory.cc: libtcpfinaggr.so successfully loaded
D/        : external/chromium/net/socket/tcp_fin_aggregation_factory.cc,: TCP Fin Aggregation initializing method was found in libtcpfinaggr.so
D/TCPFinAggregation: netstack: TCPFinAggregation is 1, Version 5.0.1
D/TCPFinAggregation: system property net.tcp.fin.aggregation.wait was set, value: 20
D/TCPFinAggregation: system property net.tcp.fin.aggregation.close was set, value: 300
D/TCPFinAggregation: netstack: CloseUnusedSockets is ON, (TCPFinAggregation), Version 5.0.1
D/TCPFinAggregation: Failed to get network status! received ret: -6
D/Socket_Pool: netstack: CloseUnusedSockets is ON
D/Socket_Pool: netstack: system net.statistics value: 0
D/Socket_Pool: netstack: CloseUnusedSockets is ON
D/Socket_Pool: netstack: system net.statistics value: 0
D/        : external/chromium/net/http/http_getzip_factory.cc: libgetzip.so successfully loaded
D/        : external/chromium/net/http/http_getzip_factory.cc,: GETzip initializing method was found in libgetzip.so
D/        : netstack: Getzip is: ON, Version: 5.0.1
I/        : netstack: LIB_MGR - Lib loaded: qnet-plugin.so
D/        : netstack: Caching Of Redirection is: ON, Version: 5.0.1
D/        : netstack: Early Connections is: ON, Version: 5.0.1, Param: 3
--------- beginning of /dev/log/main
D/dalvikvm: GC_CONCURRENT freed 274K, 27% free 8889K/12044K, paused 3ms+23ms, total 81ms
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x415678b0)
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: java.lang.RuntimeException: Debug crash
E/AndroidRuntime: 	at org.floens.chan.ui.b.ac.onClick(DeveloperSettingsController.java:74)
E/AndroidRuntime: 	at android.view.View.performClick(View.java:4421)
E/AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:17903)
E/AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:730)
E/AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime: 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5225)
E/AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
E/AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
E/AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)
I/Process : Sending signal. PID: 31453 SIG: 9
I/dalvikvm: Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.n.onProvideKeyboardShortcuts
W/dalvikvm: VFY: unable to resolve interface method 12058: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.n.onSearchRequested
W/dalvikvm: VFY: unable to resolve interface method 12060: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.n.onWindowStartingActionMode
W/dalvikvm: VFY: unable to resolve interface method 12064: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm: Could not find method android.view.Window.setStatusBarColor, referenced from method org.floens.chan.ui.i.d.a
W/dalvikvm: VFY: unable to resolve virtual method 12081: Landroid/view/Window;.setStatusBarColor (I)V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x001a
D/dalvikvm: DexOpt: unable to opt direct call 0x008d at 0x3a in Lorg/floens/chan/ui/i/d;.a
I/dalvikvm: Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.widget.fx.getDrawable
W/dalvikvm: VFY: unable to resolve virtual method 426: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm: Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.widget.fx.getDrawableForDensity
W/dalvikvm: VFY: unable to resolve virtual method 428: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.av.a
W/dalvikvm: VFY: unable to resolve instanceof 163 (Landroid/graphics/drawable/RippleDrawable;) in Landroid/support/v7/widget/av;
D/dalvikvm: VFY: replacing opcode 0x20 at 0x000c
I/dalvikvm: Could not find method android.content.Context.getColorStateList, referenced from method android.support.v7.c.a.b.a
W/dalvikvm: VFY: unable to resolve virtual method 299: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method org.floens.chan.ui.toolbar.Toolbar.setElevation, referenced from method org.floens.chan.ui.toolbar.Toolbar.d
W/dalvikvm: VFY: unable to resolve virtual method 21735: Lorg/floens/chan/ui/toolbar/Toolbar;.setElevation (F)V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x007d
D/libEGL  : loaded /vendor/lib/egl/libEGL_adreno.so
D/libEGL  : loaded /vendor/lib/egl/libGLESv1_CM_adreno.so
D/libEGL  : loaded /vendor/lib/egl/libGLESv2_adreno.so
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:316>: EGL 1.4 QUALCOMM build: LNXBUILD_AU_LINUX_ANDROID_JB_2.6_RB1.04.03.00.144.009+PATCH[ES]_msm8960_JB_2.6_RB1_CL4169980_release_ENGG (CL4169980)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: 17.01.10.SPL
I/Adreno-EGL: Build Date: 12/17/13 Tue
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/jb_2.6_rb1.10
I/Adreno-EGL: Local Patches: 579c35762619098d011c9c2a718d817a52a65028 Merge "Merge e6898912278420151291719929e1eb6163c56cc2 on remote branch"
I/Adreno-EGL:                  b075f07ef0d826864515aea57fd03e3d1caed533 Merge e6898912278420151291719929e1eb6163c56cc2 on remote bran
D/OpenGLRenderer: Enabling debug mode 0
I/dalvikvm: Could not find method android.view.View.drawableHotspotChanged, referenced from method org.floens.chan.ui.view.ThumbnailView.drawableHotspotChanged
W/dalvikvm: VFY: unable to resolve virtual method 11742: Landroid/view/View;.drawableHotspotChanged (FF)V
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0000
I/dalvikvm: Could not find method android.content.Context.getDrawable, referenced from method org.floens.chan.ui.view.ThumbnailView.setClickable
W/dalvikvm: VFY: unable to resolve virtual method 302: Landroid/content/Context;.getDrawable (I)Landroid/graphics/drawable/Drawable;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x001a
E/Volley  : [5863] a.a: Unexpected response code 404 for https://t.4cdn.org/qa/1513970132735s.jpg
D/dalvikvm: GC_CONCURRENT freed 5211K, 51% free 5443K/10940K, paused 3ms+3ms, total 34ms
D/dalvikvm: GC_CONCURRENT freed 1239K, 44% free 6222K/10940K, paused 3ms+2ms, total 26ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 15ms
D/dalvikvm: GC_CONCURRENT freed 1140K, 35% free 7129K/10940K, paused 2ms+2ms, total 44ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 21ms
D/dalvikvm: GC_CONCURRENT freed 1702K, 32% free 7474K/10940K, paused 2ms+2ms, total 42ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 25ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 27ms
D/dalvikvm: GC_CONCURRENT freed 1978K, 32% free 7544K/10940K, paused 3ms+2ms, total 37ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 22ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 24ms
D/dalvikvm: GC_FOR_ALLOC freed 438K, 30% free 7671K/10940K, paused 32ms, total 32ms
I/dalvikvm-heap: Grow heap (frag case) to 10.728MB for 1127536-byte allocation
I/dalvikvm: Could not find method android.widget.CompoundButton.drawableHotspotChanged, referenced from method android.support.v7.widget.SwitchCompat.drawableHotspotChanged
W/dalvikvm: VFY: unable to resolve virtual method 12284: Landroid/widget/CompoundButton;.drawableHotspotChanged (FF)V
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0006
D/dalvikvm: GC_CONCURRENT freed 1183K, 25% free 9093K/12044K, paused 2ms+5ms, total 79ms
D/dalvikvm: GC_CONCURRENT freed 1998K, 24% free 9264K/12044K, paused 3ms+3ms, total 48ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 30ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 24ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 27ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 24ms
I/dalvikvm: Jit: resizing JitTable from 4096 to 8192
D/dalvikvm: GC_CONCURRENT freed 2087K, 22% free 9404K/12044K, paused 3ms+3ms, total 59ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 46ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 42ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 22ms
D/dalvikvm: GC_FOR_ALLOC freed 1845K, 31% free 8355K/12044K, paused 33ms, total 33ms
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x415678b0)
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: java.lang.RuntimeException: Debug crash
E/AndroidRuntime: 	at org.floens.chan.ui.b.ac.onClick(DeveloperSettingsController.java:74)
E/AndroidRuntime: 	at android.view.View.performClick(View.java:4421)
E/AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:17903)
E/AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:730)
E/AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime: 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5225)
E/AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
E/AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
E/AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)
I/Process : Sending signal. PID: 31954 SIG: 9
I/dalvikvm: Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.n.onProvideKeyboardShortcuts
W/dalvikvm: VFY: unable to resolve interface method 12058: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.n.onSearchRequested
W/dalvikvm: VFY: unable to resolve interface method 12060: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.n.onWindowStartingActionMode
W/dalvikvm: VFY: unable to resolve interface method 12064: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm: Could not find method android.view.Window.setStatusBarColor, referenced from method org.floens.chan.ui.i.d.a
W/dalvikvm: VFY: unable to resolve virtual method 12081: Landroid/view/Window;.setStatusBarColor (I)V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x001a
D/dalvikvm: DexOpt: unable to opt direct call 0x008d at 0x3a in Lorg/floens/chan/ui/i/d;.a
I/dalvikvm: Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.widget.fx.getDrawable
W/dalvikvm: VFY: unable to resolve virtual method 426: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm: Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.widget.fx.getDrawableForDensity
W/dalvikvm: VFY: unable to resolve virtual method 428: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.av.a
W/dalvikvm: VFY: unable to resolve instanceof 163 (Landroid/graphics/drawable/RippleDrawable;) in Landroid/support/v7/widget/av;
D/dalvikvm: VFY: replacing opcode 0x20 at 0x000c
I/dalvikvm: Could not find method android.content.Context.getColorStateList, referenced from method android.support.v7.c.a.b.a
W/dalvikvm: VFY: unable to resolve virtual method 299: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method org.floens.chan.ui.toolbar.Toolbar.setElevation, referenced from method org.floens.chan.ui.toolbar.Toolbar.d
W/dalvikvm: VFY: unable to resolve virtual method 21735: Lorg/floens/chan/ui/toolbar/Toolbar;.setElevation (F)V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x007d
D/libEGL  : loaded /vendor/lib/egl/libEGL_adreno.so
D/libEGL  : loaded /vendor/lib/egl/libGLESv1_CM_adreno.so
D/libEGL  : loaded /vendor/lib/egl/libGLESv2_adreno.so
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:316>: EGL 1.4 QUALCOMM build: LNXBUILD_AU_LINUX_ANDROID_JB_2.6_RB1.04.03.00.144.009+PATCH[ES]_msm8960_JB_2.6_RB1_CL4169980_release_ENGG (CL4169980)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: 17.01.10.SPL
I/Adreno-EGL: Build Date: 12/17/13 Tue
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/jb_2.6_rb1.10
I/Adreno-EGL: Local Patches: 579c35762619098d011c9c2a718d817a52a65028 Merge "Merge e6898912278420151291719929e1eb6163c56cc2 on remote branch"
I/Adreno-EGL:                  b075f07ef0d826864515aea57fd03e3d1caed533 Merge e6898912278420151291719929e1eb6163c56cc2 on remote bran
D/OpenGLRenderer: Enabling debug mode 0
I/dalvikvm: Could not find method android.view.View.drawableHotspotChanged, referenced from method org.floens.chan.ui.view.ThumbnailView.drawableHotspotChanged
W/dalvikvm: VFY: unable to resolve virtual method 11742: Landroid/view/View;.drawableHotspotChanged (FF)V
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0000
I/dalvikvm: Could not find method android.content.Context.getDrawable, referenced from method org.floens.chan.ui.view.ThumbnailView.setClickable
W/dalvikvm: VFY: unable to resolve virtual method 302: Landroid/content/Context;.getDrawable (I)Landroid/graphics/drawable/Drawable;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x001a
E/Volley  : [5881] a.a: Unexpected response code 404 for https://t.4cdn.org/qa/1513970132735s.jpg
D/dalvikvm: GC_CONCURRENT freed 5249K, 51% free 5426K/10940K, paused 2ms+14ms, total 41ms
D/dalvikvm: GC_CONCURRENT freed 1248K, 44% free 6207K/10940K, paused 3ms+2ms, total 25ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 22ms
D/dalvikvm: GC_CONCURRENT freed 1142K, 35% free 7113K/10940K, paused 2ms+2ms, total 57ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 30ms
D/dalvikvm: GC_CONCURRENT freed 1719K, 32% free 7441K/10940K, paused 3ms+3ms, total 42ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 18ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 19ms
D/dalvikvm: GC_CONCURRENT freed 1963K, 32% free 7526K/10940K, paused 2ms+2ms, total 36ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 27ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 27ms
D/dalvikvm: GC_CONCURRENT freed 1921K, 31% free 7652K/10940K, paused 2ms+3ms, total 39ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 18ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 23ms
D/dalvikvm: GC_CONCURRENT freed 1973K, 30% free 7726K/10940K, paused 2ms+3ms, total 44ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 32ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 32ms
D/dalvikvm: GC_CONCURRENT freed 1921K, 29% free 7853K/10940K, paused 3ms+2ms, total 40ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 28ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 28ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 28ms
I/dalvikvm: Jit: resizing JitTable from 4096 to 8192
D/dalvikvm: GC_FOR_ALLOC freed 1816K, 34% free 7255K/10940K, paused 42ms, total 43ms
I/dalvikvm-heap: Grow heap (frag case) to 10.322MB for 1127536-byte allocation
I/dalvikvm: Could not find method android.widget.CompoundButton.drawableHotspotChanged, referenced from method android.support.v7.widget.SwitchCompat.drawableHotspotChanged
W/dalvikvm: VFY: unable to resolve virtual method 12284: Landroid/widget/CompoundButton;.drawableHotspotChanged (FF)V
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0006

**Comment by Floens** [comment]
I can only see the exception caused by pressing the exception button in the developer settings. (Which should be removed LOL).

**Comment by Floens** [comment]
I've implemented #390 so this shouldn't be necessary anymore.
