### ISSUE TITLE
Using back button on board editor does not reset boardspinner

### ISSUE THREAD

**Issue by JustinCheng12345** [Floens/Clover#39]
1.Set there are more than one board in boardspinner (Assume a,g,k).
2.Select the last board (Select k).
3.Go to board editor and remove that or more board (Remove g,k/k).
4.Press back button.

For removing board k case, boardspinner will show 'Add more...'.
For removing board g,k case, indexoutofboundsexception will be thrown.

Using the up button will automatically select the first board.

**Comment by Floens** [comment]
The board spinner is now updated with an event, completely fixed.
