### ISSUE TITLE
Add crash reporting.

### ISSUE THREAD

**Issue by Floens** [Floens/Clover#390]
Add crash reporting, that automatically logs the crash.

Add an opt-in checkbox when starting up Clover, and a toggle in the settings.

[acra](https://github.com/ACRA/acra) seems the best library for this.
Make sure that nothing is logged but the device model, android version, clover version, and the stacktrace. Do not send the device id.

**Comment by andyklimczak** [comment]
Did you want to setup [acralyzer](https://github.com/ACRA/acralyzer/wiki) for the reports to be sent to also? Or just do email reports?

**Comment by Floens** [comment]
I'll probably setup acralyzer, yes.
