### ISSUE TITLE
Req: Clicking X (clear) button twice in search should exit search

### ISSUE THREAD

**Issue by USER762341** [Floens/Clover#393]
Currently only the back arrow can exit search mode. Hitting the clear button (X) twice should also clear search mode so the user doesn't have to reach across the UI.

**Comment by Floens** [comment]
I don't agree. The cross is there to clear the text field. When the text field is empty, the opacity of the cross also increases.

You can use the back button of the toolbar or the device to close the search.

This behavior is consistent with apps like Telegram, or just the default search field provided by google.
