### ISSUE TITLE
Cannot reorder and remove sites.

### ISSUE THREAD

**Issue by VictorHartman** [Floens/Clover#394]
As this is work in progress this seems more like a "to do" list. This is just some things I noticed after using it for some time. 

1. Cannot remove sites
2. ~~Cannot remove boards~~
3. It's possible to add boards when none are selected (case in point: all boards are already added).
4. The boards seem to be sorted after the board that is put on the first position of the list. E.g. https://imgur.com/GfdFkS7

clover version 2.3.1-81e88848

**Comment by Floens** [comment]
Thanks. Yes I'm aware of these issues, but it's nice to have them noted down anyway.

>Cannot remove boards
They should be swipable to unsave. Does that not work?

**Comment by VictorHartman** [comment]
Swipe to remove does indeed work. A tooltip could be a good addition.

**Comment by Floens** [comment]
>It's possible to add boards when none are selected (case in point: all boards are already added).

Did you mean that it still shows the snackbar with "0 boards added" if you don't select any boards on the add screen?

**Comment by VictorHartman** [comment]
Yes. The "add" button should be non clickable when no boards are selected. And the FAB should maybe also disappear when all boards are already added.

**Comment by Floens** [comment]
Removing sites will be in another issue, because it's a lot of work.
