### ISSUE TITLE
[Request] - Please allow the option to relocate the download button in the media viewer

### ISSUE THREAD

**Issue by handpain** [Floens/Clover#396]
I browse clover using a 7 inch tablet in landscape mode in bed often, and I often find myself having to reach with my left hand all the way across the screen towards the download button if I want to save a pic/webm and my right hand is otherwise occupied or if I'm laying comfy on my right side with my left hand supporting the tablet with the other side of it touching the bed - a position which makes it hard to use the right hand. But from this position I can pretty much browse clover comfortably using my left hand fingers alone- except for saving media, which requires to me to awkwardly shift my left hand fingers towards the far edge of the screen to reach for that download button, constantly. It causes some real strain on my fingers after awhile because I'm saving images and webms constantly when browsing. And when browsing while laying on my back I either do that too or keep my right hand in position just to save images when I could be resting it or doing something else with it.

I find myself constantly wishing I could just move that download icon all the way to the left before the filename or so as it would make things so much easier and relieve a lot of strain on my hands and fingers, I could then browse much more comfortably without having to get into these constant straining motions everytime I need to reach across to save an image or webm, because it would be right there in easy reach. I tried to find if there was an option for this in clover and clover dev build appearances/layouts options but there isn't so I really hope you can add that as an option or something because right now the only way to save media is that download icon which isn't in the most ideal position at times.

Thanks for your consideration

**Comment by Floens** [comment]
Hm I'm not sure about this. It's normal material design to have the back button on the left, and the primary buttons on the right. We would need to do a bunch of stuff to the toolbar code to move a single icon to the left, and I don't think it's worth it.

**Comment by handpain** [comment]
I see that makes sense. Well what about some other way to save images/webms besides the download icon, like standard holding down on it to open up the save option? If that wouldn't be even more work than messing with the toolbar code that is. And I understand that it's normal material design to have it there but I find myself never using that back button in the image viewer actually because I just always tap on the image itself to close it, which is why an additional save image feature if you long press on the image itself would be as helpful as changing the download icon location because it wouldn't strain my fingers anymore than closing the image does now. Or even what about an option in the settings to move the filename to the right and both the download button and menu button to the left where the back button is in the media viewer? That way even more of clovers functions would be accessible with just the left hand fingers alone.

If none of those options are worth doing without messing with the code a bunch then I understand. I don't want to be a bother about this it just would be nice to have an alternative way to save media.

**Comment by Floens** [comment]
Later for when the image viewer is redone we can think about having another gesture to save a file. For now, I'll close this issue.
