### ISSUE TITLE
V1 captcha require double entry for keyboard to popup

### ISSUE THREAD

**Issue by c933103** [Floens/Clover#397]
Not sure if it is just me or a more universal problem, but when I recently started using v1 captcha in the clover app, after clicking the send button and the captcha is shown, it either take about 20-40 seconds before the keyboard start to popup (during the waiting time the text field cannot be selected either), or need to go back and then resend in order to make the captcha show up. What's wrong?

1. Enable v1 captcha in clover
2. type a reply
3. hit send button
4. the keyboard does not show up immediately

Android version: 6.0.1
Phone model: Sony F8132
Clover version: 2.1.3
Keyboard app: cedime
Native rom unrooted no xposed nor other similar things

**Comment by Floens** [comment]
That Clover version is very old, and the v1 captcha is soon disfunctional.
The waiting time might be related to a network call.

**Comment by Floens** [comment]
It's not gone, so I'm going to close this issue.
###### rip
