### ISSUE TITLE
add not javascript captcha

### ISSUE THREAD

**Issue by PajeetStreetshitter** [Floens/Clover#401]
# hello **sir** please add version 2 of captcha without javascript thank you **sir** or me and my boys will find where you live and shit on your street 💩💩💩 nothing personnel **sir**

**Comment by Floens** [comment]
hello kind sir, 
this was added to dev, https://github.com/Floens/Clover/commit/9ffe4ec060ed2974fe56a8d2d6a3b6b0c94a9231
release soon, patient please
thank yuo sir
