### ISSUE TITLE
Getting into pinned threads from inside thread.

### ISSUE THREAD

**Issue by waterjmwater** [Floens/Clover#402]
I was hoping that in the future there'd be an easier way to get into the pinned threads menu from inside of a thread. I just upgraded from Clover_v1.2.11 to the latest version. In 1.2.11 all I needed to do was press the pin symbol and the menu would come up and I'd be able to go into any of my pinned threads. 

In the latest version I either have to back out of  the thread and then bring up the menu or press the pin button twice, once to unpin and one to pin it. Another downside to this is that it will repin the thread, making it drop down to the bottom of the menu, this did not happen in 1.2.11.

In my opinion the best option would be to make it so that if you swipe left while inside a thread, the menu comes up since I don't think that swiping left does not do anything at the moment.

**Comment by Floens** [comment]
You can swipe from the left side of the screen to open the drawer.

**Comment by waterjmwater** [comment]
That brings me back to the catalog of open threads, I am looking to get into the menu for bookmarked threads.

**Comment by Floens** [comment]
Just like you can open the drawer from the board, you can from the thread. Make sure you start your swipe from the left edge of the screen.

**Comment by waterjmwater** [comment]
Yep, got it. Thanks!

**Comment by Floens** [comment]
This also worked for the old version btw.
