### ISSUE TITLE
Add support for JS "extensions"

### ISSUE THREAD

**Issue by thedragondildoboard** [Floens/Clover#403]
Just wanted to suggest allowing support for Clover extensions for things like (You) counts and such (i.e things you won't add because autism)

It's a big thing to add but I think it would be stellar to have more autonomy and convenience with using your app.
8.1.0
v2.3.1-85e15caa

**Comment by Floens** [comment]
Providing extensions in another programming language is not something I'll add. Anything we want can be implemented without the need of some extension system.
