### ISSUE TITLE
webm playback interrupt music

### ISSUE THREAD

**Issue by c933103** [Floens/Clover#404]
Is it possible to play webm muted so that background music applications can continue to play music when clover playing webm?

**Comment by Floens** [comment]
Since Oreo there's an api to allow just that. Was implemented in https://github.com/Floens/Clover/commit/fef2187ee02d12124d885da3e6126ffd29e5b8e7#diff-b43561cda5c36392cf4a2e8bfe58fc9aL377 for the next release.
