### ISSUE TITLE
[Question]How to disable split scteen?

### ISSUE THREAD

**Issue by c933103** [Floens/Clover#410]
Android 4.3, Xperia V, Clover 2.3.1
![screenshot_2018-02-07-04-56-19](https://user-images.githubusercontent.com/1525293/35883770-6ae11cf2-0bc3-11e8-84cb-909bbb9f3983.png)
See the screenshot, in catalog, the screen is splited into list of thread and a hiddened thread. How to disable the right part?
Also,  I have tried to disable the swipe away threadview  option in advanced setting,  but I can still go back to the catalog by simply swiping after disabled that, how to change it?

**Comment by Floens** [comment]
This is the sliding pane layout. You can slide the right part to the left and back. 

If you don't like it, you can change the layout mode in the settings to phone layout.

**Comment by c933103** [comment]
I see thanks
