### ISSUE TITLE
App unresponsive

### ISSUE THREAD

**Issue by TheGooGLP** [Floens/Clover#413]
App becoming unresponsive

Viewing replies to a post in any thread and then returning to the thread will cause the app to become unresponsive, meaning no scrolling, swiping or clicking. Closing the app via Android is possible

Update to Android 8.0 on Moto X. Install latest version of app. view replies on any thread, return to thread.

Android version: 8.0.0
Phone model: Moto X 4 (XT 1900-7)
Clover version: 2.3.1

**Comment by Floens** [comment]
This is a duplicate of #360

**Comment by TheGooGLP** [comment]
Turns out you were right. For some reason the update to 8.0 disabled animations completely. after restoring my usual settings it worked fine. 
Thanks!
