### ISSUE TITLE
4chan won't open (server error) 

### ISSUE THREAD

**Issue by AcSagulo** [Floens/Clover#415]
Can't enter 4chan through clover but opens normally in browser

Clover was working normally until i switched to discord then back, i kept getting a server error but i can open 4chan.org fine in chrome

Just Launch clover as you would

Android version: Android 7.0 
Phone model: SM-G928c 
Clover version: v2.3.1

**Comment by Floens** [comment]
This might be #407

**Comment by Floens** [comment]
Could you execute the steps https://github.com/Floens/Clover/issues/407#issuecomment-362919222 ?

>Possibly, but why am i getting the problem now i wonder.

might be that hiro upped the cloudflare protection level, causing it to sometimes trigger.

**Comment by AcSagulo** [comment]
I used psiphon proxy and clover seems fine, i guess ill use this as a workaround for now.

**Comment by Floens** [comment]
Most definitely the cloudflare issue, closing this as a duplicate or #407
