### ISSUE TITLE
Request for persistent webm mute switch

### ISSUE THREAD

**Issue by Akariii** [Floens/Clover#416]
Is it possible to make the mute toggle persistent? If I click unmute, leave the webM, then click on another webm, I have to unmute again. Breaks the UX flow. Would be better if it remembered and if it had an option to mute/unmute all by default. Thanks, hope this is the right place to post this.

**Comment by Floens** [comment]
Added with https://github.com/Floens/Clover/commit/272f02258a8f5a5e887131c9de3d254f4e8d8599
