### ISSUE TITLE
Android O persistent notification problem needs prioritized

### ISSUE THREAD

**Issue by thedragondildoboard** [Floens/Clover#418]
It sucks not being able to just check for new posts on my watch list.

**Comment by Floens** [comment]
I don't understand.

**Comment by thedragondildoboard** [comment]
It's not possible to get persistent notifications when you're running Android 8, and I remember reading about how you were de-prioritizing Android 8 notifications in favor of UI changes.

**Comment by Floens** [comment]
>It's not possible to get persistent notifications when you're running Android 8

that's not true

the notification doesn't need to be persistent any more. it will be made so that it only shows when there is content, and not the empty state.

**Comment by thedragondildoboard** [comment]
@Floens I don't get ANY notifications, and K have everything enabled
