### ISSUE TITLE
Error posting

### ISSUE THREAD

**Issue by oluapris** [Floens/Clover#426]
Whenever I make a post Clover gives me an error, but the post still goes through as if someone else made it. Tried restarting my phone but that still didn't fix it.

Android version: 7.0
Phone model: Samsung Galaxy S7
Clover version: 2.3.1

**Comment by Floens** [comment]
Probably related to #407

**Comment by oluapris** [comment]
Don't really get how it's a Cloudflare issue if I can post from the dev version perfectly fine.

**Comment by Floens** [comment]
Well, the normal version works fine for me. The thing that's different is the user agent.

**Comment by oluapris** [comment]
So my phone's causing the problem then? Fug.
