### ISSUE TITLE
Script error?

### ISSUE THREAD

**Issue by c933103** [Floens/Clover#430]
![screenshot_20180224-174044](https://user-images.githubusercontent.com/1525293/36628913-0c29c608-198a-11e8-9b6b-598992313ecc.png)

Sometines I am getting a number of  "@ 0: Script error" in captcha page as shown in the attached screenshot. While it doesn't actually matter, and it does not affect anything, what does it mean?

Android version: 8.0.0
Phone model: Xperia XZ1compact
Clover version: 1.3.2

**Comment by Floens** [comment]
It shows that when `window.onerror` was called, but has since been removed because like you said, it isn't actually an error.
