### ISSUE TITLE
[site request] arisuchan.jp

### ISSUE THREAD

**Issue by aliceisfollowingit** [Floens/Clover#431]
Hello, I would love support for arisuchan.jp in the future.
Here is the [repo](https://github.com/arisu-dev/arisuchan).
I think if your have any question, you could ask them on the [[meta] board](https://arisuchan.jp/q/).
Thanks :smile:.

**Comment by Floens** [comment]
it's based on vichan, so getting support.

**Comment by jtalowell** [comment]
This was added by #506 and is available in the [dev build](https://floens.github.io/Clover/#dev).
