### ISSUE TITLE
Error: You were warned. You must first view this warning to post again

### ISSUE THREAD

**Issue by chausies** [Floens/Clover#448]
When trying to post, I get red text "Error: You were warned. You must first view this warning to post again", as can been seen in this screenshot: https://i.imgur.com/9kpILCo.png

But where can I view the warning to get rid of this?

Using Clover v2.3.1 on LG V20.

**Comment by c933103** [comment]
Use web browser on your device or via a computer in the same network to try to make a post and then you would be presented with the warning that you can click to view.

**Comment by c933103** [comment]
See also #429
