### ISSUE TITLE
Images stuck loading on first attempt

### ISSUE THREAD

**Issue by GringoSuave** [Floens/Clover#45]
When attempting to open images the first time, the image will be stuck loading. Circle at the top right continues swirling but no blue line indicating any actual loading is occurring. Canceling the image load then immediately opening the image again will instantly load the image correctly.

**Comment by Floens** [comment]
What android version are you using on what device?

**Comment by GringoSuave** [comment]
This occurs on my 4.4.2 VZW Galaxy S4, Moto G running 4.4.4, and my Nexus 7 running 5.0.2

**Comment by Floens** [comment]
Weird, I don't have this issue on my device. Are you using the newest version, v1.2.6?

**Comment by GringoSuave** [comment]
Yes, it has been occurring for more than a month now

**Comment by Floens** [comment]
Turning HTTPS off in the advanced settings (settings > menu > advanced settings) seems to fix it for some people.

**Comment by plsng** [comment]
Also happens to me on Android 5 using a p4wifi.

**Comment by GringoSuave** [comment]
Testing out the lack of HTTPS for a day I have come to the conclusion that it is a snake oil treatment. It feels like there are just as many moments of being stuck as before. The best option atm is to open images in browser.

**Comment by Floens** [comment]
Have you waited for at least 10sec before retrying? The circle but no progressbar means it's connecting.

**Comment by GringoSuave** [comment]
Yes I am waiting, the circle spins but it appears to mean nothing unless I
see the blue progress bar near the top

**Comment by GringoSuave** [comment]
Just cleared data and everything seems to be ok, I'll try it out for 24hours like before with HTTPS on to see if it stays fixed

**Comment by Floens** [comment]
Can you test if it works in this version?
https://github.com/Floens/Clover/releases/download/v1.2.6_no_release/Clover_v1.2.6_image_loader_fix.apk
I replaced the image loader library in this version.

**Comment by AnonTheCuck** [comment]
Had the same issue. Can confirm that this version fixed the problem for me.

**Comment by Floens** [comment]
Great. I'll upload a new version to google play / f-droid in a minute.

**Comment by GringoSuave** [comment]
Since clearing the app data I haven't had any issues with images loading.

**Comment by AnonTheCuck** [comment]
Nevermind, the issue returned for me, but I think I know why.

Recently my IP has been flagged by cloudflare for "browser checks". These
checks only run while I'm connected to wifi, and will delay all requests
until it completes.

https://www.dropbox.com/s/7hnt86b54v7xb3i/Screenshot_2015-02-01-00-32-36.png?dl=0

I guess I'm just going to have to stop using Clover over wifi.

Since clearing the app data I haven't had any issues with images loading.

—
Reply to this email directly or view it on GitHub
<https://github.com/Floens/Clover/issues/45#issuecomment-72330919>.
