### ISSUE TITLE
Restore Clover from Titanium Backup

### ISSUE THREAD

**Issue by ElRattin** [Floens/Clover#452]
I made a backup with titanium backup
after restoring data+app clover force closed.
i restored only the app, and clover said to me there was an update version (it was the same one!).
i downloaded it, and then i restored only data with titanium backup.
with this procedure it works fine but with clover v2.3.0 there isn't this problem

thanks floens
Android version: 7.0
Clover version: v2.3.1-89ae7a29

**Comment by Floens** [comment]
Make sure you have the correct package name.

**Comment by ElRattin** [comment]
Titanium says 2.3.1-89ae7a29 but when you restore the app it's actually 3cc3c6a0
so it seems it's a titanium bug
thanks
