### ISSUE TITLE
Dev app doesn't work on CM12.1

### ISSUE THREAD

**Issue by ElRattin** [Floens/Clover#453]
Like several apps even clover dev doesn't work on CM12.1
the app causes bootloop 
the problem is described  here
https://gitlab.com/fdroid/fdroiddata/issues/969#note_45686081

Thanks again Floens
Android version: CM 12.1

**Comment by Floens** [comment]
This doesn't look like an issue with Clover.

**Comment by ElRattin** [comment]
Many apps have the same issue, it started in november
For example yalp store had this problem but in the last versions it works well.
it isn't a clover bug but it's in the Google’s build tools you use.

**Comment by Floens** [comment]
We use recent build tools. Is clover using a version that can be updated with a fix?

**Comment by ElRattin** [comment]
i don't know!
i will build it and let you know m8

**Comment by ElRattin** [comment]
The last build solved the apk build problem
thanks
