### ISSUE TITLE
2chan.net support

### ISSUE THREAD

**Issue by karrarkazuya** [Floens/Clover#458]
New site request

Please add support for http://www.2chan.net

**Comment by Floens** [comment]
Do they have an api?

**Comment by karrarkazuya** [comment]
Not as far as i know but they have their source code on github. Also they got an app on the google play store so there most be a way they did it

**Comment by beschoenen** [comment]
This might help http://jun.2chan.net/script/

**Comment by c933103** [comment]
#424

**Comment by Floens** [comment]
whoops sorry, closing as a duplicate for #424
