### ISSUE TITLE
Uploading images will not work anymore.

### ISSUE THREAD

**Issue by Avexinfinty** [Floens/Clover#478]
Error posting Error: Upload Failed. 

Clover has stopped working since yesterday with the photos I post. I've tried with multiple images, but it comes up with the same error code. Might be on just my end though, but I've tried with multiple versions of clover including 2.3.1. 

[Just posting with any words and a picture will not post at all and give me the error.]

Android version: 8.1.0
Phone model: OnePlus 5T Model A5010
Clover version: 3.0.1 and 2.3.1-dae-462e
[Clover Posting Error.zip](https://github.com/Floens/Clover/files/1959434/Clover.Posting.Error.zip)

**Comment by Floens** [comment]
Currently an issue with the site, see the announcement.
