### ISSUE TITLE
Captcha not loading

### ISSUE THREAD

**Issue by diadaren** [Floens/Clover#48]
I think it's because of the new auth. system

**Comment by Floens** [comment]
Was fixed in v1.2.6

**Comment by Floens** [comment]
Spoke too soon, it's indeed broken again.

**Comment by plsng** [comment]
Thanks, moot!

**Comment by jefer590** [comment]
is not moot anymore, more like jewgle or the new admins

**Comment by Floens** [comment]
It's google's 'fault', actually.

**Comment by Oxopoha** [comment]
I am somewhat curious how it rebroke.

**Comment by davidmyers9000** [comment]
I'm on android 4.4.2 Samsung galaxy nexus, and I'm fed up with this crap! I just wanted to engage with the community tonight and this is really turning me off. Maybe you should do something about it and not comment about it!

**Comment by davidmyers9000** [comment]
Jk only joking, but the captcha is really broken

**Comment by maddpiratekidd** [comment]
Yeah it's busted

**Comment by Floens** [comment]
Fixt https://github.com/Floens/Clover/commit/47ec05b2e40244726690b030f983751e0674d4ca
Now using a more foolproof method
