### ISSUE TITLE
No proper name for site settings in ui.

### ISSUE THREAD

**Issue by TheLastZombie** [Floens/Clover#482]
In Settings > Sites > 4chan there's a setting titled "a". I assume it's not supposed to be there? If it is, a proper title would be helpful, I'm assuming it has something to do with the API (v2 JS, v2 no JS)?

![screenshot_20180430-203434](https://user-images.githubusercontent.com/8181990/39443829-0e47d074-4cb6-11e8-8a26-60245a9bf664.png)

**Comment by Floens** [comment]
Yes, this is fetched from reflection (wasn't finished yet) and reflection after proguard yields short letters like a.
