### ISSUE TITLE
Request: Default Post Option

### ISSUE THREAD

**Issue by lehitoskin** [Floens/Clover#489]
It'd be handy to have a way to make every post use a default option, say, `since4pass`. I don't know how this could be done generically for use with sites other than 4chan, but I think it'd be useful.

**Comment by Floens** [comment]
There could be an option below the default name option that does the same but for the Options field.

**Comment by Floens** [comment]
Closing as a duplicate of #504
This issue was first but the other one has an extra suggestion.
