### ISSUE TITLE
impossible captions

### ISSUE THREAD

**Issue by vorticalbox** [Floens/Clover#49]
Really though after trying 10 I gave up, what sort of dark magic is this shit?

http://postimg.org/image/5j2lyx34z/

**Comment by plsng** [comment]
I get that stuff on my desktop as well, I think it's because Google has too little information about you so it assumes you're a bot and/or wants you to create a Google account. They're really almost impossible to solve.

**Comment by Montanax** [comment]
No idea if you already solved the problem but I fixed it in my own app by changing the "User-Agent" header to "Android" in the HttpRequest to *www.google.com/recaptcha/api/fallback?k=6Ldp2bsSAAAAAAJ5uyx_lx34lJeEpTLVkP5k04qc*

I got 1 word captchas again after changing that. Hope that helps.

**Comment by Floens** [comment]
Ayy that does the trick.
I already tried changing the user agent to chrome/firefox, adding some other headers but that didn't work, but just a plain simple Android does.
Thanks! Will push a fix for this soon.

**Comment by Floens** [comment]
Fixt https://github.com/Floens/Clover/commit/c37c1b77ae424bcc19ad679a87d61c7c12d4e539
