### ISSUE TITLE
Add sushigirl.us

### ISSUE THREAD

**Issue by lc-guy** [Floens/Clover#499]
https://sushigirl.us
It's standard vichan despite the custom homepage, so there shouldn't be any problems. 

Is there a way to implement "overboard"-style boards, which combine all threads from every board on the website into one feed? It's /kaitensushi/ on there, for example.

**Comment by jtalowell** [comment]
This was added by #506 and is available in the [dev build](https://floens.github.io/Clover/#dev). At the moment there's no support for boards like /kaitensushi/ so that was left out.
