### ISSUE TITLE
Cannot connect after unlocking phone

### ISSUE THREAD

**Issue by 5685C4A059D5** [Floens/Clover#501]
After locking the phone for a while, upon unlocking, Clover won't connect (stays on loading for a while before displaying "Network error").
After about 30s it returns to normal.

Android version: 8.1
Phone model: Essential PH-1
Clover version: 3.0.1 dev

**Comment by Floens** [comment]
Does not seem like a clover issue, clover doesn't have any special code related to this and only uses common http libraries.
