### ISSUE TITLE
Portrait mode isn't functioning properly on tab S

### ISSUE THREAD

**Issue by ukkoclap** [Floens/Clover#52]
Hello, 

The portrait mode isn't functioning properly on the Tab S 8.4 (SM-T700) which has a QHD display. When I'm holding it in portrait mode it thinks it's in landscape mode. Attached a picture to eloborate.
![screenshot_2015-02-13-00-41-34](https://cloud.githubusercontent.com/assets/10984882/6179507/20b52dbc-b31a-11e4-89f3-e8238e319f68.png)

**Comment by Floens** [comment]
Working as intended. Clover looks at the available width of the window and then decides if it's double or single column. You can force the mobile mode in advanced settings if you want.
