### ISSUE TITLE
Photo being rotated in clover app.

### ISSUE THREAD

**Issue by c933103** [Floens/Clover#528]
1. Take a photo with default camera app of Xperia phone (attached image is the photo) ![dsc_0028](https://user-images.githubusercontent.com/1525293/43356570-89816bf8-92a5-11e8-92ec-9ce9b30f0270.JPG)
2  Check gallery. The photo is displayed upright (screenshot attached) ![screenshot_20180728-203301](https://user-images.githubusercontent.com/1525293/43356577-b849ae6e-92a5-11e8-95aa-4f7398c715d8.png)
3. Launch clover. Select the photo 
Expected outcome: image remain upright
Actual Result: It go sideways, see attached screenshot ![screenshot_20180728-203317](https://user-images.githubusercontent.com/1525293/43356591-f3f9af4a-92a5-11e8-846f-dff423c0a887.png)

Android version: 8.0.0
Phone model: XZ1 Compact
Clover version: 3.0.0

**Comment by Floens** [comment]
That's a very old issue actually https://github.com/Floens/Clover/issues/150

**Comment by c933103** [comment]
Seems like even github rotated the image

**Comment by c933103** [comment]
close as duplicate
