### ISSUE TITLE
Long captcha

### ISSUE THREAD

**Issue by ukkoclap** [Floens/Clover#53]
The captcha in the clover app use to be one short word but now its two words which can get abit long sometimes to type every time on a tablet/phone.

When I open 4chan in a browser like Chrome in Android I only get one short word in captcha or hitting the checkbox sometimes works. I'm not sure which party the fault lies but I thought reporting this might be of some help and hip fully get back to just one captcha word. Or

 would you think that it would be a possibility to add the captcha like in the browser with a tickbox in the foreseeable future that would really enhance the usage experience of the app!

**Comment by Floens** [comment]
Google is playing a hard game with the captchas.
Clover uses the noscript fallback for its captchas. You can check that by: disable your adblocker, disable javascript on boards.4chan.org, going in incognito mode and opening a board. The captcha to create a new thread should be the same that clover uses.
