### ISSUE TITLE
"API parse error" for 4chan /g/,/aco/, /co/,/fit/, /his/, /m/,/x/

### ISSUE THREAD

**Issue by c933103** [Floens/Clover#532]
As of writing, those boards are currently accessible via browser but not clover. Some other boards can be accessed via clover normally
clover version 3.0.0

**Comment by Floens** [comment]
Will probably be fixed soon by 4chan.

**Comment by daktah** [comment]
Same thing, but additionally /pol/ /o/ /k/ and /diy/. /b/ /s/ /wsg/ and /gif/ seem intact (because of course porn would still be up). I also cannot seem to access them in browser as well, so Hiroshimoot probably screwed up or the CIA is having a giggle.

**Comment by notstevek** [comment]
FFLLOOOOEEEENNNS

/o/ too

(yeah I know it's not your fault, just obligatory memeing)
