### ISSUE TITLE
Arisuchan is giving https error

### ISSUE THREAD

**Issue by OpenUp596** [Floens/Clover#534]
![screenshot_2018-07-30-17-31-54](https://user-images.githubusercontent.com/33358726/43403785-a995886e-941e-11e8-8e4d-94c2c17b5b64.png)

**Comment by OpenUp596** [comment]
Same for Lainchan
![screenshot_2018-07-30-17-35-23](https://user-images.githubusercontent.com/33358726/43403918-fc933930-941e-11e8-9d10-9a4d96327b07.png)

**Comment by Floens** [comment]
Works fine for me, must be your device.

**Comment by OpenUp596** [comment]
Ok then, sushichan is fine tho
