### ISSUE TITLE
Looks like 4chan pass login is broken

### ISSUE THREAD

**Issue by ShootPara** [Floens/Clover#538]
4chan pass login responds with Unknown Error for no apparent reason. 

Survives clear data. Happens in Clover and Clover dev. 

Clear data, attempt to login with a 4chan pass. 

Android version: 7.0
Phone model: sm-t117
Clover version: dev 3.0.1

**Comment by ShootPara** [comment]
Disregard, it's working again? Perhaps confounded by 4chan outright banning Pass logins from some exit nodes from CyberGhost? Would appreciate a little more disgnostic information on 4chan Pass login failures in general but the functionality seems to not be broken.

**Comment by Floens** [comment]
It's just a general network error.
