### ISSUE TITLE
[Request] Please add 2ch.hk imageboard support

### ISSUE THREAD

**Issue by zettts** [Floens/Clover#542]
2ch.hk imageboard clients are dead and not maintained by any developer.  Please add support for this board if possible.

**Comment by rrrmeow** [comment]
I double this respectable lord.

**Comment by MEWop** [comment]
so looong :(

**Comment by MEWop** [comment]
;(((

**Comment by Floens** [comment]
You're not helping.

**Comment by zettts** [comment]
@Floens How can we help? Please provide build with this pull request and we can help with testing from our side.

**Comment by MEWop** [comment]
> You're not helping.

I'm not cool developer like You, so I can't help, sorry :( I just waiting, when You verify and merge this **anselmov** commit and update Clover - best imageboard browser ever.

**Comment by Sakurachansky** [comment]
Bump

**Comment by Floens** [comment]
It was merged.
