### ISSUE TITLE
Lollipop external storage write permission issue

### ISSUE THREAD

**Issue by aruv42** [Floens/Clover#55]
Because Lolipop policy. App can't write file in external sdcard. I hope you can add permission to write in sdcard for lolipop

**Comment by Floens** [comment]
I'll look into this, I haven't worked with the document provider api yet.

**Comment by Esjitu** [comment]
Was going to request this as well.

**Comment by rychon** [comment]
Also, some of my folders where I attempt to download a thread of pictures ends up not saving any pics. But still makes folder, and thread is still up.

**Comment by Floens** [comment]
#178 has a bit more information on this, closing this one as a duplicate.
