### ISSUE TITLE
Troubles adding 8chan

### ISSUE THREAD

**Issue by frey1337** [Floens/Clover#554]
Hey there, im loving the app and i use it daily for browsing 4chan,
I wanted to add 8chan but i have troubles with that, no boards shows up and when im trying to add them via link i always get 404 error,
Could someone please explain what i am doing wrong? Thanks

**Comment by Floens** [comment]
Enter the board code and then add it.

**Comment by frey1337** [comment]
Ooh this that simple, i was copying links and playing with the syntax to make it work, thank you
