### ISSUE TITLE
Thumbnail Compression Image Swap Not Working

### ISSUE THREAD

**Issue by n3rt46** [Floens/Clover#556]
Images can be "hidden" inside of other images by having every other pixel be of another image. This is possible because 4chan resizes uploaded images such that a different image is visible in the thumbnail from the one visible in the full-size image.
Here's an example:
https://desuarchive.org/qa/thread/2317742/#q2317742

Reproducing this problem is easy, but may be device-specific. Simply find an image as described and try to view it first as the thumbnail in thread-view and again full-sized by tapping on the image.

Android version: 6.0.1
Phone model: SM-N910V
Clover version: 3.0.1 F-Droid

**Comment by Floens** [comment]
This is not applicable in Clover because the thumbnails and the full resolution images are simply displayed at other resolutions than the site does.

**Comment by bakugo** [comment]
This trick actually has nothing to do with resolution, it's done via the gamma chunk in a PNG file.
It's done by making half the pixels the first image, and making the rest the second image but extremely dark. Then applying the gamma filter so the pixels of the first image become extremely bright and the pixels of the second image become normal.
4chan's thumbnailer ignores the gamma value so you get the first image, but browsers apply it so you get the second. Clover doesn't apply it like browsers do, so it doesn't work.

**Comment by Floens** [comment]
Interesting, didn't know that. Thanks!
