### ISSUE TITLE
Crash when playing back video (webm/gif?)

### ISSUE THREAD

**Issue by c933103** [Floens/Clover#559]
Steps to reproduce the issue:
1. Navigate to https://boards.4chan.org/a/thread/178592900#p178605336 within clover app
2. Try to play the attached file
What occured: Clover crashed
Expected behavior: File being playback 

Android version: 8.0.0
Phone model: XZ1 Compact
Clover version: 3.0.0

**Comment by Riotous** [comment]
@c933103 Using 3.0.1 from F-Droid. No crash here. It's a gif.

**Comment by c933103** [comment]
Seems like bug in my phone that caused all video players to malfunction for unknown reason.
