### ISSUE TITLE
Pinned threads with ID

### ISSUE THREAD

**Issue by tapabug** [Floens/Clover#56]
How can I have pinned threads with ID, like on the webpage
http://floens.github.io/Clover/assets/img/phone3.png
/g/39894014
It's easier to look on the boards archive with the ID
thanks

**Comment by Floens** [comment]
That's not possible unfortunately. You can rename pins by long pressing them though.

**Comment by tapabug** [comment]
Can I ask why?
For accessing a thread don't you need a thread number?
https://github.com/4chan/4chan-API
http(s)://a.4cdn.org/board/thread/threadnumber.json

**Comment by Floens** [comment]
I don't understand you. What is it that you want to achieve?

**Comment by tapabug** [comment]
that [generateTitle] (https://github.com/Floens/Clover/blob/dev/Clover/app/src/main/java/org/floens/chan/core/model/Post.java#L43)
return "/" + post.board + "/" + post.no;
