### ISSUE TITLE
Network error on boards

### ISSUE THREAD

**Issue by fullfy** [Floens/Clover#563]
Some boards are giving a network error.

The boards that aren't showing this are: /v/, /vg/, /b/, /pol/, /s4s/, /biz/, /3DCG/, /a/, /adv/, /c/, /jp/, /lit/, /mu/, /p/, /po/, /sci/, /trv/, /vp/, /w/, /wsgl/, /wsr/, /d/, /h/, /hc/, /ic/, /soc/ and /t/. All the others are showing network error, be on wifi or data.
Checked on browser and they load up.

Checking all boards

Android version: 8.1.0
Phone model: Mi A1
Clover version: 3.0.1

**Comment by Floens** [comment]
4chan issue, not Clover. The API is giving invalid JSON, will probably be fixed soon.
