### ISSUE TITLE
4chan not reloading properly

### ISSUE THREAD

**Issue by lakitu13** [Floens/Clover#578]
I had some issues with boards and threads not refreshing, on clover /v/ was stuck as if the site had been on lockdown for a few hours again, but I open some of the threads and I see that they have many more posts then reported on the catalog and have been archived for a while. /h/ was reloading just fine, except for the one thread I had on watch. 
All that started happening after I went to sleep. I solved the issue by reinstalling, this time through fdroid, but still thought it worth reporting. 

I'm not sure how to reproduce it. 

Android version: 6.0.1
Phone model: galaxy j2 prime sm-g532mt
Clover version: 3.0.1

**Comment by Floens** [comment]
Sometimes 4chan gives off the wrong caching headers, causing Clover to only use the data it cached. Clearing the cache in the app details screen fixes this.

**Comment by lakitu13** [comment]
On further inspection I believe I found the cause on this issue. 
manually set back the phone clock > the active board(or maybe the first board in the list?) and watched threads stops updating

Setting it back to auto makes it update again. 
If the app is installed while the clock is NOT set to auto it works fine.

Daylight saving time was delayed here in Brazil this year but many phones still had the default DST date, so I had to set the clock back in time and caused this.

**Comment by lakitu13** [comment]
> Sometimes 4chan gives off the wrong caching headers, causing Clover to only use the data it cached. Clearing the cache in the app details screen fixes this.
Oh, didn't see your reply. Yeah I tried looking into clearing the cache from the app and forgot about the button in the app details, I'll close this for now.
