### ISSUE TITLE
Cache cap

### ISSUE THREAD

**Issue by ElectroPug** [Floens/Clover#59]
There's this problem that the app won't load any content if the cache size reaches around 51/52 MB. Currently on android 4.4.2.

**Comment by Floens** [comment]
I cannot reproduce this, are there any significant entries in the log?
Clover now loads up to 50MB of cache files. And when a file gets added to the cache when its size is more than 50MB, Clover will clean up the oldest files until the cache gets below 50MB again.

**Comment by mwalker55** [comment]
I have been having this same issue.  I have to manually go in and delete app data once it reaches around 50 MB or else it won't load any content.  Had this issue on a Nexus 7 running most recent Android version.

**Comment by Floens** [comment]
This was fixed.
