### ISSUE TITLE
Odd Pinned Threads menu behaviour. 

### ISSUE THREAD

**Issue by TheBlueGhost** [Floens/Clover#6]
This bug happens on a Samsung Galaxy S2, running Cyanogenmod 10.2.
As the application is started, everything is fine. The Pinned Threads menu can be pulled out and any threads there accessed. If one of the items in the menu is selected, it works as intended. After a thread is picked a seemingly random amount of times (from 1 to about 5) the menu ceases to work. It still slides out, but threads can not accessed. Tapping on any pinned threads gives no result.

**Comment by Floens** [comment]
Most probably fixed with the new drawer, closing.
