### ISSUE TITLE
4chan pass not allowing posting

### ISSUE THREAD

**Issue by Griphen116** [Floens/Clover#60]
just updated and logged into my 4chan gold pass, and every time i try to post, it says "invalid captcha"
i'm on a galaxy s4 active running os 4.4.2

**Comment by Floens** [comment]
I cannot reproduce this. Have you tried logging out and in again?

**Comment by Griphen116** [comment]
yes, i've tried a couple times, logging in and closing the app, restarting the app then logging in, a lot of different times, but it always gives me the same message

**Comment by Floens** [comment]
Does it work in a browser?

**Comment by Griphen116** [comment]
yes, it does, and i'm using chrome on my desktop for what that's worth

**Comment by Floens** [comment]
My pass expired, I can log in but 4chan gives an error when posting "pass expired". So I thought everything worked. I will purchase a pass soon to test this again.
