### ISSUE TITLE
4chan(nel) post ban only in clover

### ISSUE THREAD

**Issue by c933103** [Floens/Clover#609]
Basic part of this report:
1. Use clover to try to make a reply in 4chan /a/ (via both wifi or cellular)
2. Error: Error: You are banned
3. Try to use browser to make the same post in the same IP address with the same device
4. The post can be made
5. Thus it seems to indicate something is wrong with clover that make it possible to post via browser but not clover 

Additional behavior observation:
1. Try to post with clover via mobile network
2. You are banned warning
3. Switch to airplane mode and then switch it back, presumably acquired new IP address
4. Post can be made via clover onto 4chan
5. Try to use the same session (IP address) to make a new post
6. The same "you are banned" warning
7. Need to redo step 3 to go back to step 4

Note that during the entire time, posting via movile browser is not affected. What's wrong?

Xperia XZ1 Compact, Clover 3.0.0

**Comment by traktori** [comment]
I'm experiencing the same problem.

**Comment by c933103** [comment]
See >>>/qa/2502795  seems like problem of 4chan new testing function

**Comment by Floens** [comment]
Seems like a thing the 4chan devs have fixed now https://boards.4channel.org/qa/thread/2502795#p2503099
