### ISSUE TITLE
Can't post on 4channel boards

### ISSUE THREAD

**Issue by Ashtonio** [Floens/Clover#657]
[short and descriptive title]
Getting Error posting: Unable to resolve host "sys.4chan.or: No address associated with that hostname

[detailed explanation of the issue]
Pretty much getting this error when I'm trying to reply in a thread. 
[steps to reproduce the issue]
1. Reply in a thread
2. Gets the error when trying to post. 

Android version: Android 9
Phone model: SM-G975F
Clover version: 3.0.2

**Comment by Ashtonio** [comment]
Ok, it only occurs when I'm on mobile data, I changed to WiFi and I was able to post fine, anyone know why?

**Comment by Adamantcheese** [comment]
It's likely a DNS block from your wireless provider. This isn't a problem with Clover.

**Comment by Ashtonio** [comment]
Ah I see, I'll close the issue then.
