### ISSUE TITLE
[request] content overview grid

### ISSUE THREAD

**Issue by krautbernd** [Floens/Clover#666]
show all the content posted in a thread like in a gallery. maybe due a upswipe while opened a picture.

**Comment by Astridchan** [comment]
If by content you mean images then this feature already exists, see:

![IMG_20190408_152607](https://user-images.githubusercontent.com/40862101/55723901-dae71800-5a12-11e9-9702-8211e663fa15.jpg)
![IMG_20190408_152628](https://user-images.githubusercontent.com/40862101/55723907-df133580-5a12-11e9-89b8-4d8aa6b906f2.jpg)

You can also download every image posted in a thread by clicking the three dot menu in the gallery view and selecting "download album"

**Comment by krautbernd** [comment]
jep, thx
