### ISSUE TITLE
[Request] Folders for Boards and Bookmarks

### ISSUE THREAD

**Issue by seniorm0ment** [Floens/Clover#671]
The ability to categorize boards into folders would be nice. This would be useful to separate nsfw and sfw boards as well as find certain boards quicker.

The ability to categorize bookmarked threads into folders would be nice as well. It would be nice to be able to have it automatically folder them by board (or make custom ones).
So say you make a post in /b/, it then makes a bookmark folder called /b/.. outside of that folder it would show the number with the red indicator if you were replied to In any of the threads. You then click into the folder to see all the bookmarked threads in that folder.

**Comment by Adamantcheese** [comment]
This is a partial duplicate of both #312 and #571.
