### ISSUE TITLE
Feature: A small thing

### ISSUE THREAD

**Issue by iloveclover** [Floens/Clover#68]
Hey Floens. I would like to ask a small favor for you.

You know how everytime you post, your post is highlighted? I was wondering if you can add an option to turn that off or on.

I absolutely LOVE how the dark theme on your app looks, but the highlighted posts just distract me a little bit too much.

Thanks Floens. I appreciate everything you have done so far honestly.

**Comment by Floens** [comment]
Try the other themes please, it's not as obnoxious as before.
