### ISSUE TITLE
Increase posting timeout for 4g/data

### ISSUE THREAD

**Issue by lovepupils** [Floens/Clover#693]
[short and descriptive title]
Posting with Clover on 4g/lte data can result in timeout, even if post is just text.

[detailed explanation of the issue]
When switching from Wifi to data, it often happens that posting on 4chan fails due to timeout error.
WIth or without images attached, and even if 4g is quite fast (I can see on my phone the upload speed being in MB/s). Turning data off/on (maybe acquiring a new ip?) solves it only temporarily.
Note: I am not banned, posting from Firefox mobile works just fine all the time with 4g/data.

[steps to reproduce the issue]
- write post (op or reply)
- solve captcha (no js)
- hit post
- wait
- Error posting: timeout.

Android version: 6.0
Phone model: PLK-L01 (Honor 7)
Clover version: v.3.0.2 or dev up to April 23 2019 (tried both)

**Comment by K1rakishou** [comment]
After looking at the code I noticed that we already have 30 seconds timeout (not 15 as I thought).
https://github.com/Floens/Clover/blob/d42b9dfa069c4d157279d5d03ff7294bfe05c477/Clover/app/src/main/java/org/floens/chan/core/site/http/HttpCallManager.java#L38

 Another thing that I've noticed is this line: 
>// Disable SPDY, causes reproducible timeouts, only one download at the same time and other fun stuff
>.protocols(Collections.singletonList(Protocol.HTTP_1_1))

https://github.com/Floens/Clover/blob/d42b9dfa069c4d157279d5d03ff7294bfe05c477/Clover/app/src/main/java/org/floens/chan/core/cache/FileCache.java#L57
Maybe it is somehow related to this problem and we should disable it in HttpCallManager as well?

**Comment by lovepupils** [comment]
![Screenshot_2019-04-23-13-43-49](https://user-images.githubusercontent.com/7249501/56578523-26cabd00-65ce-11e9-9bd8-8cbfa98ca351.png)
Attached a screenshot.

I can confirm it takes at least 30s to timeout.
Once it happens, all subsequent tries fail with timeout until switching data off/on or switching to WiFi.

Note: the upload traffic only lasts a couple second, the following seconds until timeout generate zero network traffic.

**Comment by c933103** [comment]
Is it possible to increase the timeout to 90 seconds on GPRS/EDGE network?

**Comment by K1rakishou** [comment]
@c933103 Yes it is possible, but it may not help. There is a hunch that the timeout has nothing to do with it. 
I guess we should start with updating the okhttp (3.10.0 -> 3.14.1). If it doesn't help then try disabling the SPDY. And If it does not help too then we can add an option to increase the timeout.

**Comment by K1rakishou** [comment]
So I build a debug APK with couple of possible fixes (see https://github.com/Floens/Clover/issues/693#issuecomment-486561736)
Here it is: 
[app-default-debug.zip](https://github.com/Floens/Clover/files/3132152/app-default-debug.zip)
(adb install -r app-default-debug.apk to install it)

@lovepupils @c933103 Could you please try it out?

**Comment by lovepupils** [comment]
Thank you @K1rakishou I will try it for some days and report back.

**Comment by lovepupils** [comment]
It's already happening after an hour or so using the app.
Logs uploaded here:

https://pastebin.com/AYszDFE8

**Comment by K1rakishou** [comment]
@lovepupils 
Damn, that's unfortunate. Well if that didn't help, increasing the timeout will probably not help too. But just in case, here is an apk with 300 seconds (instead of 30) timeout:
[app-default-debug.zip](https://github.com/Floens/Clover/files/3163061/app-default-debug.zip)

**Comment by lovepupils** [comment]
Hi, this seems to work except in the past days my ISP got rangebanned so I cannot post at all.
But I did not get a timeout error until then, as far as I could test.

**Comment by K1rakishou** [comment]
@lovepupils 
Huh, that's interesting. And how long do you wait until the post gets sent?

**Comment by lovepupils** [comment]
Eventually I got into a new IP range with DHCP lease from my provider (an European country Vodafone) and now I can post again.
Posts go through in around 3 to 5 seconds without pictures, and a couple seconds more with pics (upload speed is fast).
No timeout so far.

**Comment by K1rakishou** [comment]
@lovepupils 
Well, I guess there is a point in making the timeout a separate option now.

**Comment by lovepupils** [comment]
Sorry to come back to this after it's been closed by a commit,
but it's still happening to me randomly on that apk you gave me with timeout 300.
The difference is that it takes all that time for it to timeout, but after 10 seconds I can already tell it's not going to post.

The only difference I found was (but I'm not sure it's everytime it fails) that before submitting a post that will timeout, the captcha instructions will often be in my native language instead of english (and I also forced english in app settings). I wonder if this is a coincidence or not.

**Comment by lovepupils** [comment]
More on this:
I tried back the regular app and there still is a difference in behavior (in positive).

When the "timeout" posting happens, in regular app even if I hit "reload" on thread, all successive tries fail with timeout, until i turn data off/on or join a wifi network.
With your debug apk, if I see that the posting is going to timeout, if I hit reload on thread, I can immediately post again and have success, usually quite fast as usual (1-2 s until post succesful).
