### ISSUE TITLE
[Feature request] Override custom implementation of text selection menu

### ISSUE THREAD

**Issue by Astridchan** [Floens/Clover#699]
In MIUI (possibly other manufacturer Android skins too) the stock Android text selection menu has been replaced with the manufacturer's own menu implementation. This sucks with Clover because you lose the very useful "Quote" option from the text selection menu that lets you highlight only parts of a post to quote. I have noticed that Google's own apps and the Wikipedia app, among others, are overriding the MIUI text selection menu to bring back the stock implementation. Could this be added to Clover?

Below: Clover, Chrome, Wikipedia
![clover_chrome_wikipedia](https://user-images.githubusercontent.com/40862101/57178600-b187a380-6e7b-11e9-8acc-f736e82bd292.png)

**Comment by Adamantcheese** [comment]
Duplicate of #637. Please don't make duplicate feature requests of ones you have made in the past; modify your old request with new details instead.

**Comment by Astridchan** [comment]
I don't consider it to be a duplicate but two separate features / issues, even though they both involve the text selection menu. #637 is simply about adding a new action, "web search", to the text selection menu, whereas this one is about the menu being completely replaced by the manufacturer's own implementation, so that you lose *any* custom action Clover has in the text selection menu. Adding #637 won't fix #699, and fixing #699 won't add #637.

It looked into this, and since the issue is with MIUI and seems to involve a lot of work to fix it's probably infeasible to do so, but I'll keep the issue open to let Floens look into it and give his say about it.

https://stackoverflow.com/questions/45165150/devices-with-android-miui-and-setcustomselectionactionmodecallback
http://en.miui.com/thread-233931-1-1.html

**Comment by Adamantcheese** [comment]
My mistake then. Apologies.

**Comment by qduborper** [comment]
Hello @Astridchan  ! do you know if this has been resolved on latest MIUI 12 version ? 
Or did you find a workaround for make it working on MIUI devices without a custom ROM ?
Best regards

**Comment by Astridchan** [comment]
Hi @qduborper , I am currently running Xiaomi.eu ROM on my phone which is a custom ROM based on the official MIUI 12 builds, and the custom text selection options are available, at least on Kuroba (Clover fork). I cannot say for certain if they're available on official MIUI 12 though.

![IMG_20201212_040035](https://user-images.githubusercontent.com/40862101/101969715-9d4a8180-3c2e-11eb-8102-fa339bf4dc27.jpg)
