### ISSUE TITLE
problem loading threads and images/webm's on lg g3 with lollipop update

### ISSUE THREAD

**Issue by ObituaryPhoenix** [Floens/Clover#70]
As the title says, I have been having trouble loading threads and images or videos since the lollipop update came for my lg g3, wondering if this is aan app issue cuz all other things load fine with the new update on other apps

**Comment by Floens** [comment]
Clover uses Volley for loading threads, and okhttp for the images.
Volley is also used in Google Play, and okhttp in numerous other applications.
Can you try to disable https in the advanced settings? (settings > menu > advanced settings)

**Comment by ObituaryPhoenix** [comment]
There is no option for that in my Wi-Fi settings or anywhere else in my
phone I don't believe

**Comment by Floens** [comment]
Whoops sorry, I meant in the settings of Clover.

**Comment by ObituaryPhoenix** [comment]
Turned off https and it's still loading slowly

**Comment by Floens** [comment]
Tracking in #92
