### ISSUE TITLE
Problem with "Go to image" button on tablets.

### ISSUE THREAD

**Issue by EfronC** [Floens/Clover#700]
Problem with the ↵ button when you open an image on Gallery Mode

When you open a thread, go to gallery mode, and open an image, there is button with the symbol ↵ that if you click, it takes you to the reply with the image. This button works perfectly on my phone, but when i try to use it on my tablet, it simply close the image. Interestingly, if you open a thread from Archive, there it works perfectly, not sure if resolution has anything to do. this problem has been there for a long time, i was just waiting that it was matter of an update due to it working on my Phone, but now it seems it's a bug.

[Attached an example on the Gif] Open a thread from main view → click on Gallery Mode button on the thread → Open an image → Click on ↵ button → Image closes instead of going to the image.

![ezgif com-optimize](https://user-images.githubusercontent.com/5926318/57347250-40641c80-7117-11e9-9efd-aa35d6998402.gif)

Android version: 7.1.1
Tablet model: Lenovo YT-X703F
Clover version: 3.0.2

PD: This doesn't have anything to do with this issue, but i want to evade create another 3 issues since i don't think they are very important: 

1.-Another issue is that if you go to /gif/, and open a webm with sound, and the click on the Home button, it doesn't stop the video, it's still sounding until you open the app again and pause it. Don't think its wrong, just maybe not something you expect.

2.- Is there a list of websites supported for the app? Sometimes, when i open the app after an update, the changelog says "More sites added", but i don't know which ones, Maybe add that to the readme?

3.- A simple question: Any advance with letting choose a folder from an SD card to save media from the app? I really want that feature.

**Comment by Adamantcheese** [comment]
This looks like it's a problem specifically with the Split Mode navigation style (as opposed to Slide/Phone mode). There's no "previous" controller for it to look for images in, so AlbumViewController's goToPost method returns null and doesn't do what it should. Will probably fix and submit a PR, doesn't look hard.

As for your other points:

1) Please submit an issue for this. You don't need to be super thorough like this one (the video helped a lot).

2) [These are the currently supported sites.](https://github.com/Floens/Clover/tree/dev/Clover/app/src/main/java/org/floens/chan/core/site/sites)

3) SD cards are notoriously stupid to deal with on Android. There are other apps that let you do a "local sync" between a folder and your SD card, like FolderSync, which is one workaround for it.

**Comment by EfronC** [comment]
The main reason as for point 3 (SD card save), is because having another app running in background just to pass files from a folder to another could cause performance problems, especially on phones/tablets that have started to age, or that already have another sync apps working. But well, that's no the topic in this issue.

I'll create another issue for point 1 as you asked, but sincerely i'm not sure how to define it.
