### ISSUE TITLE
Audio of webm still sounding when suspending the app.

### ISSUE THREAD

**Issue by EfronC** [Floens/Clover#702]
The audio of a webm keeps when you suspend the app.

Not sure how to define the issue, since i don't know what could be the issue, but i think is more like something you don't expect, if you open a webm with sound, and then click home button when is playing, the webm doesn't stop, it keeps playing with all and sound, this is probably an unexpected behavior more than anything.

Go to /gif/ → Seach for a webm with sound → Open it, and let it start playing → Click the home button of your phone/tablet → webm still playing on background.

Android version: 7.1.1
Tablet model: Lenovo YT-X703F
Clover version: 3.0.2

**Comment by tim-elmer** [comment]
This also seems to happen if a webm with audio was playing (even muted), and a phonecall takes place afterwards with speakerphone. Force killing the app stops audio.
