### ISSUE TITLE
Videos crashing the app

### ISSUE THREAD

**Issue by EfronC** [Floens/Clover#721]
Open a webm crashes the app

Just now, while i was browsing a thread, and happened to try to open a video, the video didn't load, and the app crashed(Asked me if i wanted to wait or close the app), i tried disabling Exo player, but still same problem, and when i tried to use the option to open with external player, while the app didn't crash, it still didn't load the video on that app. 

Yesterday(Or at least more than 24 hours ago) this wasn't happening. This is happening only on my tablet, which haven't received a single update months ago, in my phone, which has Clover Dev and receives updates almost weekly, is working perfectly, don't know if this is an issue solved in any of those updates(In which case, it would be good launch one soon, since F-Droid says last one was 3 months ago).

Steps:
- Search any webm on a thread.
- Click to open.
- The webm shows the blue bar upside that is loading, but when it ends, it just keep on a transparent screen.
- App is unresponsive.
- Few moments later crashes.

Android version: 7.1.1
Tablet model: Lenovo YT-X703F
Clover version: 3.0.2

**Comment by azumukupoe** [comment]
i have the same problem on c101pa
why was this closed without any comment?

**Comment by EfronC** [comment]
I closed it because it wasn't a problem of the app, but from my tablet, seems like my video codecs stopped working(Just a Theory), and because of that, not only Clover, but i couldn't open videos in any app, re starting my tablet solved it, but again, it wasn't related to Clover.
