### ISSUE TITLE
[Feature Request] Make the "banned" word a hyperlink to 4chan.org/banned

### ISSUE THREAD

**Issue by floppyD** [Floens/Clover#734]
Just like in desktop, that would avoid having to open the browser and typing the URL manually there.
![Screenshot_20190726-150527](https://user-images.githubusercontent.com/29208110/61972735-ae064300-afb8-11e9-8ae9-e0f06901ce0a.png)

Android version: 7.1.2
Phone model: Moto G3
Clover version: v3.0.2-0c58c619

**Comment by ghost** [comment]
Might be better if clover 
 opens the link when the error is presented, similar to the captcha popup. That way warning can be dismissed without leaving clover
