### ISSUE TITLE
[Feature Request] Use date/hour format based on phone's locale

### ISSUE THREAD

**Issue by floppyD** [Floens/Clover#735]
Just like in AdamantCheese's Kuroba.

Android version: 7.1.2
Phone model: Moto G3
Clover version: v3.0.2-0c58c619

**Comment by floens** [comment]
This is already the case, no?

**Comment by floppyD** [comment]
No, AdamantCheese changed the way it fetches date recently, now it will take your locale format in account.
Ex: Clover on left, Kuroba on right
![newf](https://user-images.githubusercontent.com/29208110/61989361-994f9c80-b004-11e9-88ec-4933d73991df.png)

**Comment by happapa** [comment]
I think it should show the dates the same way the website does.
