### ISSUE TITLE
[Bug] Clover Dev weird crashes on legacy Android version

### ISSUE THREAD

**Issue by floppyD** [Floens/Clover#736]
The latest Dev build crashes on my 4.1.2 tablet while trying to add boards or entering Settings. Can confirm that it works fine on Android 4.4.4, 7.1.2 and 9.0.
![20190726_232714](https://user-images.githubusercontent.com/29208110/61989074-5390d500-b000-11e9-8492-654fe70b69a7.gif)

Android version: 4.1.2
Phone model: GT-P6200L
Clover version: v3.0.2-0c58c619

**Comment by floens** [comment]
If you enable crash reporting then I can see the crash log.

**Comment by floppyD** [comment]
I can't, it crashes when trying to enter Settings like I mentioned.

**Comment by floppyD** [comment]
Just to add: I did some tests, 3feb3d2c was the last build without this issue, 2d462a5c and anything past it crashes the exactly same way.

**Comment by andyklimczak** [comment]
Thanks for nailing down which commit seems to cause the issue. If you comment out or revert the lines in 2d462a5, does it still crash?
