### ISSUE TITLE
Uploading a recent downloaded image throws corrupted or unsupported file type error

### ISSUE THREAD

**Issue by jefer590** [Floens/Clover#74]
Well, everytime i want to upload a image that i just downloaded in Google Chrome mobile in a thread, i always get this error:
![screenshot_2015-05-12-16-02-51](https://cloud.githubusercontent.com/assets/3887243/7600534/05362f54-f8c1-11e4-93d5-11ecdd02e3c1.png)

How to reproduce this issue:
1.- Download an image from Google Chrome Mobile
2.- Try to post the downloaded image in a thread or a new post

Device: Nexus 5
OS: Android 5.1 Lollipop

**Comment by tedgpendleton** [comment]
I have the same problem. It seems to be related to images downloaded from Google.  Images downloaded from imgur don't seem to have the same problem.

Motorola Droid Maxx
Android Version 4.4.4

**Comment by CancerousCoder** [comment]
Tested it on Xperia Z running Cyanogen Mod 12.1-20150829-Nightly-yuga, Problem not found 
Try downloading it with another browser
