### ISSUE TITLE
Loading Abnormalities

### ISSUE THREAD

**Issue by lorenz-graf** [Floens/Clover#741]
After launching the app the user can only receive network traffic for about 10 seconds after which any attempt to open threads, refresh boards, see image previews, etc. will not work. (stuck with a spinning loading indicator for threads and boards while image previews of already opened threads simply won't load at all)

This error occurs on both LTE and WLAN which are both at very acceptable speeds and stability. The application used to work perfectly fine for about a month on this phone. 

There were, and still are, a lot of threads bookmarked with the threadwatcher enabled (currently about 20 bookmarks). however it seems unlikely that the problem is to be related with this feature.

Any ideas what could cause this behaviour? Thanks in advance!

Android version: 9
Phone model: OnePlus 7 Pro / GM1913
Clover version: v3.0.2

**Comment by floens** [comment]
You can try building Clover for yourself and profiling what is wrong by attaching a profiler or looking at the startup timing logs. Unfortunately those are only available on development builds.

**Comment by lorenz-graf** [comment]
Just to be clear: any and all features, including board- and thread switching, image previews (default and gallery view within a thread), work perfectly fine and behave as intended in these first 10 seconds of starting the app.

To work around the issue the user has to quickly select a thread and scroll through the entirety of it within the 10 seconds to "pre-load" the content such as the image previews. Then this specific thread can be read.

To "fix" the problem the user has to close the app in androids open application manager to force a total reboot of the app. Then you again have 10 seconds to select a new thread and perform the workaround as described above.

Maybe the workaround information helps somehow.

**Comment by lorenz-graf** [comment]
I tried to circumvent having to setup AS and the SDK... But sure, i might take a look at it if it is an unknown problem.

**Comment by Adamantcheese** [comment]
Couple of ideas:
1) If it's 8chan, it's not going to work at all. Given that it's working for 10 seconds, this isn't the case.
2) It was working for a month before and it's a new thing that has recently appeared, despite nothing changing in the application as you're still on v3.0.2 stable, makes me think that it's an external factor. Perhaps your internet provider (DNS provider maybe?) has started blocking *chan sites as a result of recent events, but it has a delay in blocking requests for some reason. If that's the case, then it should be similar on a phone browser; could you see if that's the case?

**Comment by lorenz-graf** [comment]
First of all: Thanks for the fast responses and the constructive process.

As to 1: The problem occurs on 4chan (haven't tested other image boards since the occurance of the problem). There might be an 8ch bookmark in there tho, maybe that could cause it. I will get back to you about that.

As to 2: That is correct, the problem started occuring whithout a change of the application version. That's why i mentioned that the threadwatcher is used a lot since i assumed it could be related to an overloaded cache / storage of some sort? I haven't checked out the code if this would be possible, so it is just a blind guess.

Also as to 2: Since the WLAN and the LTE use different DNS servers and attempts to fix the problem using VPN (with multiple different countries) in combination with both WLAN and LTE did not fix the bug makes me assume the problem to be on the client side of things. The "open in browser" feature works even after the 10s (probably because the reference was caught beforehand) where within the browser all content loads and behaves as expected and is very responsive. I assume this to exclude the option of having a DNS related problem. If i should still test it within standalone browsers, let me know.

**Comment by lorenz-graf** [comment]
I might be onto sonething here: I cleared out the 8chan bookmark which fixed the problem for now. 

However since the problem occured it was never fixed temporarily through any prevous attempt so this looks really promising.

It would also kind of make sense since you can literally see the thread watcher perform its work of updating the thread statuses - thread by thread. My assumption is that some kind of network management process / class is unable to recover after attempting to update the nonexistent thread status. It would definetly make sense, also from the timing perspective of things, since it takes a few seconds to work through all those bookmarks.

I will close the thread for now since this looks really promising. However this should effect everybody that has any 8chan bookmark.
