### ISSUE TITLE
Crash upon tapping reply counter

### ISSUE THREAD

**Issue by colecovision** [Floens/Clover#743]
Clover dev crashes upon tapping the "X replies" counter, before any popup gets to be displayed.
This happens on the latest version (v3.0.2-0c58c619) and on v3.0.2-2d462a5c, but does not occur on v3.0.2-3feb3d2c.
Logcat states thus:
```
E/AndroidRuntime(8683): android.view.InflateException: Binary XML file line #24: Error inflating class org.floens.chan.ui.layout.PostRepliesContainer
E/AndroidRuntime(8683): 	at org.floens.chan.a.b.e(Controller.java:8)
E/AndroidRuntime(8683): 	at org.floens.chan.c.b.qb.b(PostRepliesController.java:5)
E/AndroidRuntime(8683): 	at org.floens.chan.c.b.qb.a(PostRepliesController.java:2)
E/AndroidRuntime(8683): 	at org.floens.chan.c.e.k.a(PostPopupHelper.java:5)
E/AndroidRuntime(8683): 	at org.floens.chan.ui.layout.ThreadLayout.a(ThreadLayout.java:41)
E/AndroidRuntime(8683): 	at org.floens.chan.b.i.p.c(ThreadPresenter.java:8)
E/AndroidRuntime(8683): 	at org.floens.chan.ui.cell.PostCell.a(PostCell.java:9)
E/AndroidRuntime(8683): 	at org.floens.chan.ui.cell.d.onClick(lambda)
E/AndroidRuntime(8683): 	at org.floens.chan.ui.layout.PostRepliesContainer.<init>(PostRepliesContainer.java:2)
```
This makes me think it could have been caused by the UI refresher commit  9ad896ecd7b6034f5390991ce6d1fa5346d56229. It might also be related to #736.

Android version: 4.4.2
Phone model: LG-D320n
Clover version: v3.0.2-0c58c619 and (up to?) v3.0.2-2d462a5c

**Comment by fuck-shithub** [comment]
Yeah. I've gotten the same issue when I decided to build Clover with #739, and from that point pressing the "X replies" crashes the app on my Amazon Fire Phone running Android 4.4.4 KitKat (unofficial LineageOS 11)

**Comment by Adamantcheese** [comment]
This may be related to a similar issue I've run into at Adamantcheese#878, where for some reason the backcolor attribute doesn't like being used in certain places. It's used in the `@drawable/dialog_full_light` declaration in `layout_post_replies.xml`.
