### ISSUE TITLE
Cannot Properly Filter Empty Subject Lines

### ISSUE THREAD

**Issue by Hitomi98** [Floens/Clover#744]
**Short and descriptive title:**
Clover cannot seem to use regex to filter empty subject lines

**Detailed explanation of the issue:**
I am trying to filter the posts on all boards such that only posts with nonempty subject lines
are visible but it seems that the app cannot properly match empty regex strings
The following do not work:
/^$/
/^(?![\s\S])/
They should match on empty strings but they don't

**Steps to reproduce the issue:**
This is what the filter screen looks like:
![filters](https://user-images.githubusercontent.com/55341971/64918048-42ef1680-d788-11e9-8dbd-acc04d59042d.png)
The "types" selected is just subject

Android version: 7.0
Phone model: SM-G935U
Clover version: v3.0.2

**Comment by Adamantcheese** [comment]
This is due to it defaulting to no match when the input string is empty (ie subject line is empty). https://github.com/chandevel/Clover/blob/d42b9dfa069c4d157279d5d03ff7294bfe05c477/Clover/app/src/main/java/org/floens/chan/core/manager/FilterEngine.java#L177-L178

**Comment by Hitomi98** [comment]
> 
> 
> This is due to it defaulting to no match when the input string is empty (ie subject line is empty).
> 
> https://github.com/chandevel/Clover/blob/d42b9dfa069c4d157279d5d03ff7294bfe05c477/Clover/app/src/main/java/org/floens/chan/core/manager/FilterEngine.java#L177-L178

Even if I enable the regex that I posted above, the filters do not work when I actually go to browse a board, posts with nonempty subject lines still show up.

**Comment by Adamantcheese** [comment]
`/^$/gmi` is not a valid regex to Clover. `gm` are not flags that are supported, only `i` is, and it will return a filter that is effectively `/^$/i`. Again, NO FILTER will match an empty string due to that code snippet.
