### ISSUE TITLE
[Feature Request] Add the option to (you) a post

### ISSUE THREAD

**Issue by owo1337** [Floens/Clover#754]
[short and descriptive title]
add the ability for the user to (you) a post.

[detailed explanation of the issue]
I use 4chan on my PC for the most part but like to use clover for mobile 4chan. I think it would be great if I could be able to manually check some of my posts that I've done on PC so I can still get notifications for them while I'm on mobile.

[steps to reproduce the issue]
N/A

**Comment by kgibson9489** [comment]
+1 to this. Just a simple way to claim a post as your own for the sake of notifications would be helpful.

**Comment by Adamantcheese** [comment]
Enable developer settings by tapping the version number several times. A new context menu item will be added to posts labeled "Save" which will do this. Be warned that you can't undo this action.

**Comment by Yoirkie** [comment]
stop being lazy, just find your own post and You it.
