### ISSUE TITLE
Captcha connection issue

### ISSUE THREAD

**Issue by oluapris** [Floens/Clover#757]
[short and descriptive title]
Captcha connection issue
[detailed explanation of the issue]
Whenever I try to post I get the following error:
"Could not connect to the reCAPTCHA service.

Please check your internet connection and reload to get a reCAPTCHA challenge."
Despite my internet connection being stable and posting working properly in a browser. Force closing the app and restarting my phone didn't help either.
[steps to reproduce the issue]
-open a thread
-submit a post
Android version: 
8.0.0
Phone model: 
SM-G930F
Clover version: 
v3.0.2

**Comment by K1rakishou** [comment]
No-js captcha is dead. Maybe it will be fixed by google, maybe not.
https://github.com/ccd0/4chan-x/issues/2500

Anyway, just switch to javascript catpcha in the site settings.

**Comment by Dotty** [comment]
>https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0

NJS captcha isn't dead as a whole. It still works in general. Just not on 4chan.

>The current key hasn't changed and it is being sent correctly, so either google banned the site or Hiro disabled it.

**Comment by im-n1** [comment]
This issue makes Clover literally garbage.

**Comment by c933103** [comment]
Seems like nojs recaptcha is now working again?
