### ISSUE TITLE
Please upgrade to a supported browser to get a recaptcha challenge

### ISSUE THREAD

**Issue by TWACC** [Floens/Clover#758]
I posted this on the wrong github page before because I haven't gotten much sleep, please excuse any further stupidity.
[detailed explanation of the issue]
I'm getting this message when I try to post.
[steps to reproduce the issue]
1.Try to post.
Android version: 4.1.2
Phone model: SCH-S968C
Clover version: 3.0.2

**Comment by Adamantcheese** [comment]
Probably the same issue as #757. See if using JS captcha works.

**Comment by TWACC** [comment]
> Probably the same issue as #757. See if using JS captcha works.

It doesn't.

**Comment by TWACC** [comment]
@Adamantcheese So what do I do now?

**Comment by K1rakishou** [comment]
@TWACC 
It should work because it works for everyone else. Make sure that you changed NoJS captcha to JS one in Settings -> Sites -> Catpcha Type

**Comment by TWACC** [comment]
@K1rakishou I have done so and it doesn't work.

**Comment by Kar1488** [comment]
> @TWACC
> It should work because it works for everyone else. Make sure that you changed NoJS captcha to JS one in Settings -> Sites -> Catpcha Type

The JS method works fine for me, but what causes this problem? I mean why isn't it working anymore? The NoJS was working yesterday and now it doesn't, is there any way to reuse or fix the NoJS method?

**Comment by Kar1488** [comment]
> @TWACC
> It should work because it works for everyone else. Make sure that you changed NoJS captcha to JS one in Settings -> Sites -> Catpcha Type

The JS method works fine for me, but what causes this problem? I mean why isn't it working anymore? The NoJS was working yesterday and now it doesn't, is there any way to reuse or fix the NoJS method?

**Comment by Kar1488** [comment]
@K1rakishou The JS method works fine for me, but what causes this problem? I mean why isn't it working anymore? The NoJS was working yesterday and now it doesn't, is there any way to reuse or fix the NoJS method?

**Comment by Adamantcheese** [comment]
I have a theory that, because of the low Android version of 4.1.2, the WebView user-agent is what is causing the issue; using a static, spoofed, but up-to-date user-agent string might resolve the problem.

**Comment by TWACC** [comment]
@Adamantcheese I have no idea what that means. Sorry for being dumb.

**Comment by Adamantcheese** [comment]
Basically, maybe your phone is too old for captcha now? If other people have the same issue on a similar Android version I have reason to believe that's why it isn't working; if what I think is correct is the case, then it might have a software workaround to get it to render.

**Comment by TWACC** [comment]
@Adamantcheese But it works fine outside of clover.

**Comment by LtPatterson** [comment]
> Basically, maybe your phone is too old for captcha now? If other people have the same issue on a similar Android version I have reason to believe that's why it isn't working; if what I think is correct is the case, then it might have a software workaround to get it to render.

This issue has been reported all the way up to Android 9 in other similar threads.

**Comment by Kar1488** [comment]
@LtPatterson So, apparently this isn't because you have an older version of android, so why is this happening? I mean is there any user out there who still uses clover and didn't get this problem? Did you got this problem? Because if someone still right now uses clover and didn't get this problem, I don't believe that it is a problem because of having an older android version.

**Comment by LtPatterson** [comment]
> @LtPatterson So, apparently this isn't because you have an older version of android, so why is this happening? I mean is there any user out there who still uses clover and didn't get this problem? Did you got this problem? Because if someone still right now uses clover and didn't get this problem, I don't believe that it is a problem because of having an older android version.

I am using Android 9 and I have the same issue. No idea why, as captcha on other apps/sites work fine for me. This just started happening a few days ago. I would appreciate an update from a dev, but given the time of year, that's asking a lot.

This issue has been documented in other reports. - #759 is the issue where captcha isn't remembered if you do select JS vs no-script this setting isn't remembered. #757 also references the same problem.
