### ISSUE TITLE
Does not remember Captcha type

### ISSUE THREAD

**Issue by xiphiidae** [Floens/Clover#759]
The Captcha type (Javascript or Noscript), under Settings->Sites->Configure->Additional Settings, defaults to Noscript after closing and reopening, even if Javascript was selected the last time the app was open. As Noscript Captcha seems to no longer work on 4chan, this effectively means I have to change this setting every time I open the app to be able to post. 

Android version: 9
Phone model: SM-G960F
Clover version: 3.0.2 and Clover dev 3.0.2-0c58c619

**Comment by Adamantcheese** [comment]
Note for Floens, see https://github.com/Adamantcheese/Kuroba/commit/3b4ce8b0535541710bb9ef5688bff3748c9d78c0, notably the JsonSettings and JsonSettingsProvider classes. If requested, I can toss that fix into PR #739.

**Comment by LtPatterson** [comment]
Confirming the issue as well. Related to #758 and #757. Additionally switching to JS Captcha makes the challenge scale incorrectly and requires the user to scroll to one side to complete the challenge if those image squares are needed (they frequently are).

Android version: 9
Phone Model: OnePlus 6
Clover Version 3.0.2

**Comment by lewri** [comment]
> Note for Floens, see [Adamantcheese@3b4ce8b](https://github.com/Adamantcheese/Kuroba/commit/3b4ce8b0535541710bb9ef5688bff3748c9d78c0), notably the JsonSettings and JsonSettingsProvider classes. If requested, I can toss that fix into PR #739.

I would suggest just putting it in. Hopefully Floens to come along eventually and push out a new version

**Comment by LtPatterson** [comment]
Agree. A new version is needed out of timeline alone. I've moved on to using Read Chan. No JS issues there and the app is nearly as good as Clover (better in some cases, worse in others). Active dev as well.

**Comment by DirtyDan1** [comment]
@Adamantcheese that fix doesn't seem to work for existing databases
userSettings is never updated, stays as `{}`, setting userSettings to `{"settings":{}}` like I get after clearing data didn't help
nothing in logcat
works fine if I clear data and re-add 4chan

**Comment by Godridge** [comment]
Still getting this issue

**Comment by lewri** [comment]
I believe a new version of Clover hasn't been released yet, which would be why the issue still exists. I believe it is fixed in the fork of this, Koruba, though.

**Comment by knasen88** [comment]
can someone  fix this already, its ridiculous. just make JS default for now.
https://github.com/chandevel/Clover/blob/088d01fa89ca43276eb9dc6c3eb6e5b028ef97a7/Clover/app/src/main/java/org/floens/chan/core/site/sites/dvach/Dvach.java#L75
a simple captchatype= javascript wouldn't bandaid fix this or?
