### ISSUE TITLE
An option to use mobile network for posting

### ISSUE THREAD

**Issue by azumukupoe** [Floens/Clover#765]
[short and descriptive title]

[detailed explanation of the issue]
Useful if your home network is banned for some reason.  
[steps to reproduce the issue]

Android version: [Find at Settings > About phone > android version]
Phone model: [Find at Settings > About phone > Model number]
Clover version: [Find at the bottom of the settings screen of Clover]

**Comment by lewri** [comment]
So you're basically asking for a tool to carry out ban evasion? (Even if yourself personally isn't banned, that's the door you'd be opening)

You could simply just turn off WiFi on your phone to achieve the same effect

**Comment by article10** [comment]
Just a VPN if your IP was banned even though you yourself 'dindu nuffin' . 
It's doubtful an individual app could even circumvent Android's WiFi settings to use 4G.
