### ISSUE TITLE
Option to disable SSL

### ISSUE THREAD

**Issue by romme** [Floens/Clover#77]
4chan is inaccessible over SSL in Russia because they want to pass it through a DPI filter. Can we get an option to disable SSL?

**Comment by Floens** [comment]
Shouldn't you enable ssl to circumvent that?
Anyway you can toggle https through settings > menu > advanced settings > use https.

**Comment by romme** [comment]
I was retarded enough not to notice that. I'm sorry. I can't use SSL because SSL is blocked precisely to prevent circumvention.
