### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by jaquerman** [Floens/Clover#771]
Can't build my version

i made a few adjustments to the most recent version but i cant compile/build it for some reason

I did some edits on the source code and when i finished i followed the steps for the build:

-  Open Android Studio
-  Click "Open an existing Android Studio project"
-  Select the file Clover/Clover/build.gradle and press OK
-  When asked, install any required tools.
-  Sync the project again and it should be ready.

and this warnings and error pop up:
-  Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
-  Warning: License for package Android SDK Platform 28 not accepted.
-  Caused by: org.gradle.process.internal.ExecException: Process 'command 'git'' finished with non-zero exit value 128

i tried to update the sdk tools but they're already updated, got the GIT and all but i don't know what is the problem... plz help
![studio64_RUePlYQLhm](https://user-images.githubusercontent.com/65313066/81866538-f33e3600-9534-11ea-84f5-b2dc02ad2e4c.png)

Clover version: v3.0.2

**Comment by Adamantcheese** [comment]
Likely you haven't set up GIT to have a user/email attached to it; see https://stackoverflow.com/a/17228373. Another option might be to change the build variant in the tab on the bottom left to be a release build instead of a dev build.
