### ISSUE TITLE
Captcha broken?

### ISSUE THREAD

**Issue by oluapris** [Floens/Clover#78]
Can't submit posts on my HTC one M8. I can enter the captcha normally, but when I press Verify, it prompts me to paste a code into an empty text box. After that I'm stuck because I have no way of confirming that I pasted the code. http://i.imgur.com/AmGC4Zz.png

**Comment by Floens** [comment]
I fixed a captcha issue in v1.2.11.
Are you on that version?

**Comment by oluapris** [comment]
I just updated it and it works fine. Thanks!
