### ISSUE TITLE
Regression: Save files no longer save to site/board folders

### ISSUE THREAD

**Issue by GallaherMike** [Floens/Clover#781]
Files are no longer saved with using folders for the site and board. This worked in older versions.

Previously there were options to save files in folders based on the site and folder. Those "features" seem to be gone, and Clover now saves all files to the same folder.

View an image. Click the download button, check the download location.

Android version: 10
Phone model: Moto z4
Clover version: 3.0.2-e950a727

**Comment by floens** [comment]
We've dropped support for it because of complications with the new storage framework forced by Google.

**Comment by K1rakishou** [comment]
~@Floens Well if you really want this feature you can use a library I wrote to deal with SAF and it's quirks - https://github.com/K1rakishou/Fuck-Storage-Access-Framework
But I'm gonna warn you - it works but it's full of hacks. (Especially the snapshots).
It's been used in kuroba for almost a year now.
It works, but sometimes I see weird crashes that I have no idea how to fix.~

Actually no, the library uses min_sdk 21.

**Comment by shatteredhalo** [comment]
This was the only reason I was still on this over Kuroka... : ( RIP
