### ISSUE TITLE
New Board Addition

### ISSUE THREAD

**Issue by Griphen116** [Floens/Clover#787]
Adding new board to 4chan list

/vrpg/ was added a week ago and haven't been able to browse on clover because the board is not in the list of available boards in the 4chan list.

Requesting either being able to add new boards or a new update that adds that to the board list.

If this feature is already available and i haven't been able to find it in the settings, please call me an idiot.

Clover Version 3.0.2

**Comment by floens** [comment]
The board list is reloaded after you restart the app. After the restart you can add it at the site settings.
