### ISSUE TITLE
Finishing CAPCHA can't submit

### ISSUE THREAD

**Issue by FuturzMinion** [Floens/Clover#79]
I'm having an issue with Clover where when I go to post I do the image capcha, and when I finish a bunch of them it asks me to copy and paste a long code into a white box. Upon doing that, I can't get the submit button to light up, therefore I can't post at all.

**Comment by Floens** [comment]
I fixed a captcha issue in v1.2.11.
Are you on that version?

**Comment by FuturzMinion** [comment]
Yes, I found out that Google Play didn't auto update it. It fixed it.
