### ISSUE TITLE
Can't unpin 404'd threads

### ISSUE THREAD

**Issue by beschoenen** [Floens/Clover#80]
I'm unable to unpin 404'd threads. I'm using the dev branch.

Just wanted to let you know.

**Comment by Floens** [comment]
May have to do with my crummy implementation of a swipe to dismiss system.
Google announced they made an reorder and dismiss system themselves for
RecyclerView, so I'll wait until that is released.

**Comment by beschoenen** [comment]
oh, i didn't know you could swipe them (that worked). but the normal toggle in the thread isn't clickable if the thread has 404'd.
