### ISSUE TITLE
Trying to verify captcha results in an "Uncaught ReferenceError"

### ISSUE THREAD

**Issue by TheYellowMenace** [Floens/Clover#88]
After verifying the captcha on certain devices, there is an error over the captcha box that reads "20:Uncaught ReferenceError: NPObject deleted @ (URL of current thread)" and the submit button is grayed out and I am unable to post. Googling the issue yielded no results.

**Comment by Floens** [comment]
Can't reproduce, probably a bug in your device's webview. What Android version and phone are you using.

**Comment by TheYellowMenace** [comment]
The device I'm using has 4.4.2. My device with lolipop works perfectly fine.
The error looks like this:
![screenshot_2015-07-26-11-50-03](https://cloud.githubusercontent.com/assets/13225662/8894896/b57f6b0e-338c-11e5-9bca-9febf6bd1e09.png)

**Comment by Floens** [comment]
What is your phone model?

**Comment by TheYellowMenace** [comment]
Coolpad 5560s,
I use it for tinkering with android, mostly.

**Comment by Floens** [comment]
The legacy captcha is now the main captcha used, so if this issue still persist try using that one.
