### ISSUE TITLE
[REQUEST] be able to mark posts as your own so they produce red "you" updates

### ISSUE THREAD

**Issue by daktah** [Floens/Clover#89]
would be very handy if you post from your computer and then switch to your phone for whatever reason because you would be able to get the distinct red updates and know when someone replied to you instead of standard updates when anyone replies to a thread.

**Comment by Floens** [comment]
This is possible if you have the developer mode enabled.
To enable developer options go to the settings and tap the version 5 times.

**Comment by daktah** [comment]
damn that was fast, and lo and behold there it is and it works perfectly. this is why you have the best app on the store. thanks!

**Comment by TheIronMarx** [comment]
This seems to no longer be possible, that or I don't see the option after enabling developer mode. Has this feature vanished since 2015?

**Comment by Adamantcheese** [comment]
@TheIronMarx See #438. The post won't be highlighted unless you reload the thread though.

**Comment by TheIronMarx** [comment]
Oh! Thank you. I wouldn't have guessed "Save" did that.
