### ISSUE TITLE
Images, gifs and webms won't load.

### ISSUE THREAD

**Issue by Uviation** [Floens/Clover#92]
Hello, I've been using clover for a long time, never had problems last night I was downloading a game, went to clover to pass time, the tech boars was taking a long time to load and other boards, images don't load nor do gifs and webms. It takes a long time to load boards and such. I have an Samsung galaxy s5. Mobile data works and I can load images

**Comment by shadow4742** [comment]
Also experiencing a issue loading images on v1.2.11 where any image will return a failed to load error. Image loading works fine directly through the website. HTC one m8

**Comment by Floens** [comment]
Might be related to #70

**Comment by Uviation** [comment]
Where can I find the advanced menu, have no option for it.

**Comment by shadow4742** [comment]
Turning off https does affect it.
HTC m8

Uviation, it is in the menu in the top right corner of the settings menu

**Comment by Uviation** [comment]
OK, turned off still the same problem

**Comment by shadow4742** [comment]
Sorry, swipe corrected doesn't to does.

Turning off https doesn't affect it*

**Comment by Floens** [comment]
Is this still a problem?

**Comment by shadow4742** [comment]
No

**Comment by Uviation** [comment]
No
