### ISSUE TITLE
Option to auto remove archived/deleted threads

### ISSUE THREAD

**Issue by wolfram221** [Floens/Clover#94]
Please add quick spoilers to material. There was never a way to decisively remove all 404 pinned threads at once, instead forced to manually remove them one by one.

**Comment by Floens** [comment]
I want to add quick spoilers, if I find room for it.
You can swipe away the pinned threads but a single button to remove all 404'ed threads would be nice I guess.

**Comment by wolfram221** [comment]
I have it set on pin if I post so I attain a fuckload of threads.

**Comment by d9h02f** [comment]
A setting to auto-remove 404'd threads could probably be useful as well.

**Comment by seanhold3n** [comment]
Possible implementation: instead of having one "X" button in the header to clear all pinned threads, have two buttons - "X<sub>404</sub>" and "X<sub>all</sub>".  Would this be a desirable change?

**Comment by Floens** [comment]
This was done.
Tapping it clears inactive threads, long holding it clears everything.
