### ISSUE TITLE
[feedback] Works nearly flawlessly on Windows 10 Mobile

### ISSUE THREAD

**Issue by hexafluoride** [Floens/Clover#97]
Not really an issue, just chiming in to say that Clover works nearly perfectly with Project Astoria save for 1. file picking and 2. WebM.

Here are some screenshots.

![wp_ss_20150812_0008](https://cloud.githubusercontent.com/assets/5571189/9236643/bd509bee-414e-11e5-999a-4c96e27050fb.png)
![wp_ss_20150812_0009](https://cloud.githubusercontent.com/assets/5571189/9236644/bd578986-414e-11e5-818d-5aac5c00ca07.png)
![wp_ss_20150812_0010](https://cloud.githubusercontent.com/assets/5571189/9236645/bd584c2c-414e-11e5-9bbc-67d1f51ab4f7.png)
![wp_ss_20150812_0011](https://cloud.githubusercontent.com/assets/5571189/9236646/bd5e253e-414e-11e5-818e-1820c2bccb48.png)
![wp_ss_20150813_0001](https://cloud.githubusercontent.com/assets/5571189/9236647/bd648780-414e-11e5-8d64-2ff6f47bb619.png)

**Comment by Floens** [comment]
Thanks for letting me know.
The file picking logic uses a very standard approach, so I think Microsoft has to fix that themselves.
And WebM support is provided with the standard VideoView class. If window phone can play WebM video files in the default video player then support is coming to VideoView.
